// Mocks generated by Mockito 5.4.6 from annotations
// in wifi/test/fitur/alarm/alarm_scheduler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wifi/fitur/alarm/penjadwal_alarm.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PenjadwalAlarm].
///
/// See the documentation for Mockito's code generation for more information.
class MockPenjadwalAlarm extends _i1.Mock implements _i2.PenjadwalAlarm {
  MockPenjadwalAlarm() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> jadwalkanSekali(
    DateTime? waktu,
    int? id,
    void Function()? panggilBalik, {
    bool? bangunkan,
    bool? tepatWaktu,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #jadwalkanSekali,
              [waktu, id, panggilBalik],
              {#bangunkan: bangunkan, #tepatWaktu: tepatWaktu},
            ),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> jadwalkanPeriodik(
    Duration? durasi,
    int? id,
    void Function()? panggilBalik, {
    DateTime? mulaiPada,
    bool? tepatWaktu,
    bool? bangunkan,
    bool? jadwalkanUlangSaatBoot,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #jadwalkanPeriodik,
              [durasi, id, panggilBalik],
              {
                #mulaiPada: mulaiPada,
                #tepatWaktu: tepatWaktu,
                #bangunkan: bangunkan,
                #jadwalkanUlangSaatBoot: jadwalkanUlangSaatBoot,
              },
            ),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> jadwalkanSekaliPada(
    DateTime? waktu,
    int? id,
    void Function()? panggilBalik, {
    bool? tepatWaktu = false,
    bool? bangunkan = false,
    bool? jadwalkanUlangSaatBoot = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #jadwalkanSekaliPada,
              [waktu, id, panggilBalik],
              {
                #tepatWaktu: tepatWaktu,
                #bangunkan: bangunkan,
                #jadwalkanUlangSaatBoot: jadwalkanUlangSaatBoot,
              },
            ),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> batalkan(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#batalkan, [id]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
