// Mocks generated by Mockito 5.4.6 from annotations
// in wifi/test/shared/services/notifikasi/penjadwal_notifikasi_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cloud_firestore/cloud_firestore.dart' as _i3;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wifi/fitur/notfikasi/notifikasi_servis.dart' as _i4;
import 'package:wifi/shared/model/transaction_model.dart' as _i8;
import 'package:wifi/shared/operasi/firebase_operasi/notifikasi_op_firebase.dart'
    as _i6;
import 'package:wifi/shared/operasi/firebase_operasi/transaction_op_firebase.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFlutterLocalNotificationsPlugin_0 extends _i1.SmartFake
    implements _i2.FlutterLocalNotificationsPlugin {
  _FakeFlutterLocalNotificationsPlugin_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseFirestore_1 extends _i1.SmartFake
    implements _i3.FirebaseFirestore {
  _FakeFirebaseFirestore_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocumentReference_2<T extends Object?> extends _i1.SmartFake
    implements _i3.DocumentReference<T> {
  _FakeDocumentReference_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NotifikasiServis].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotifikasiServis extends _i1.Mock implements _i4.NotifikasiServis {
  MockNotifikasiServis() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlutterLocalNotificationsPlugin get plugin => (super.noSuchMethod(
        Invocation.getter(#plugin),
        returnValue: _FakeFlutterLocalNotificationsPlugin_0(
          this,
          Invocation.getter(#plugin),
        ),
      ) as _i2.FlutterLocalNotificationsPlugin);

  @override
  set channelNotifikasiPenting(_i2.AndroidNotificationChannel? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #channelNotifikasiPenting,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> initNotif({required String? iconName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #initNotif,
          [],
          {#iconName: iconName},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void pantauNotifUmum(_i6.NotifikasiOpFirebase? notifikasiOp) =>
      super.noSuchMethod(
        Invocation.method(
          #pantauNotifUmum,
          [notifikasiOp],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pantauNotifUser(
    _i6.NotifikasiOpFirebase? notifikasiOp,
    String? userId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #pantauNotifUser,
          [
            notifikasiOp,
            userId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void hentikanPemantauanNotifikasi() => super.noSuchMethod(
        Invocation.method(
          #hentikanPemantauanNotifikasi,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> requestPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.NotificationAppLaunchDetails?>
      getDetailPeluncuranNotifikasi() => (super.noSuchMethod(
            Invocation.method(
              #getDetailPeluncuranNotifikasi,
              [],
            ),
            returnValue: _i5.Future<_i2.NotificationAppLaunchDetails?>.value(),
          ) as _i5.Future<_i2.NotificationAppLaunchDetails?>);

  @override
  _i5.Future<void> tampilkanNotifikasiLangsung({
    required String? title,
    required String? body,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #tampilkanNotifikasiLangsung,
          [],
          {
            #title: title,
            #body: body,
            #payload: payload,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> jadwalNotifikasi({
    required int? id,
    required String? title,
    required String? body,
    required DateTime? jadwal,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #jadwalNotifikasi,
          [],
          {
            #id: id,
            #title: title,
            #body: body,
            #jadwal: jadwal,
            #payload: payload,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> perbaruiJadwalNotifikasi({
    required int? id,
    required String? title,
    required String? body,
    required DateTime? jadwal,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #perbaruiJadwalNotifikasi,
          [],
          {
            #id: id,
            #title: title,
            #body: body,
            #jadwal: jadwal,
            #payload: payload,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> batalNotifikasi(int? id) => (super.noSuchMethod(
        Invocation.method(
          #batalNotifikasi,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> batalSemuaNotifikasi() => (super.noSuchMethod(
        Invocation.method(
          #batalSemuaNotifikasi,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> pastikanIzinExactAlarm() => (super.noSuchMethod(
        Invocation.method(
          #pastikanIzinExactAlarm,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [TransactionOpFirebase].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionOpFirebase extends _i1.Mock
    implements _i7.TransactionOpFirebase {
  MockTransactionOpFirebase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.FirebaseFirestore get firestore => (super.noSuchMethod(
        Invocation.getter(#firestore),
        returnValue: _FakeFirebaseFirestore_1(
          this,
          Invocation.getter(#firestore),
        ),
      ) as _i3.FirebaseFirestore);

  @override
  _i5.Future<void> addTransaction(_i8.TransactionModel? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTransaction,
          [transaction],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i8.TransactionModel?> getLatestPaidTransactionByUserId(
          String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLatestPaidTransactionByUserId,
          [customerId],
        ),
        returnValue: _i5.Future<_i8.TransactionModel?>.value(),
      ) as _i5.Future<_i8.TransactionModel?>);

  @override
  _i5.Future<List<_i8.TransactionModel>> getByCustomerId(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByCustomerId,
          [customerId],
        ),
        returnValue: _i5.Future<List<_i8.TransactionModel>>.value(
            <_i8.TransactionModel>[]),
      ) as _i5.Future<List<_i8.TransactionModel>>);

  @override
  _i5.Future<int> getTotalPoints(String? customerId) => (super.noSuchMethod(
        Invocation.method(
          #getTotalPoints,
          [customerId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> deleteTransaction(String? transactionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTransaction,
          [transactionId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> softDeleteTransaction(String? transactionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #softDeleteTransaction,
          [transactionId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i8.TransactionModel>> getPaketAktifCustomer(
          String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaketAktifCustomer,
          [customerId],
        ),
        returnValue: _i5.Future<List<_i8.TransactionModel>>.value(
            <_i8.TransactionModel>[]),
      ) as _i5.Future<List<_i8.TransactionModel>>);

  @override
  _i5.Future<_i3.DocumentReference<Object?>> add(
    String? collectionName,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [
            collectionName,
            data,
          ],
        ),
        returnValue: _i5.Future<_i3.DocumentReference<Object?>>.value(
            _FakeDocumentReference_2<Object?>(
          this,
          Invocation.method(
            #add,
            [
              collectionName,
              data,
            ],
          ),
        )),
      ) as _i5.Future<_i3.DocumentReference<Object?>>);

  @override
  _i5.Future<void> sisipkan(
    String? collectionName,
    String? docId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [
            collectionName,
            docId,
            data,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> update(
    String? collectionName,
    String? docId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            collectionName,
            docId,
            data,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> hapusSementara(
    String? collectionName,
    String? docId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #softDelete,
          [
            collectionName,
            docId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> hapusPermanen(
    String? collectionName,
    String? docId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [
            collectionName,
            docId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> hapusSementaraSemua(String? collectionName) =>
      (super.noSuchMethod(
        Invocation.method(
          #softDeleteAll,
          [collectionName],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> insertOrUpdateBatch(
    String? collectionName,
    List<Map<String, dynamic>>? items,
    String? idKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertOrUpdateBatch,
          [
            collectionName,
            items,
            idKey,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
