include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # GAYA KODE
    use_super_parameters: true

    # FLUTTER SPECIFIC
    use_build_context_synchronously: true

    # PENCEGAHAN BUG
    unawaited_futures: true
    hash_and_equals: true
    avoid_dynamic_calls: true
    only_throw_errors: true
    throw_in_finally: true
    cancel_subscriptions: true
    close_sinks: true
    avoid_void_async: true

    # KEBERSIHAN & PERFORMA
    always_use_package_imports: true
    directives_ordering: true
    prefer_final_fields: true
    prefer_final_locals: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  
  errors:
    # Kritis (Blocking build)
    use_build_context_synchronously: error
    unawaited_futures: error
    hash_and_equals: error
    avoid_dynamic_calls: error
    only_throw_errors: error
    throw_in_finally: error
    cancel_subscriptions: error
    close_sinks: error
    avoid_void_async: error

    prefer_const_constructors: warning
    prefer_const_constructors_in_immutables: warning


  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true