name: wifi
description: "Pengingat service rutin"
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase & Cloud
  cloud_firestore: ^6.4.1
  firebase_core: ^4.9.0

  # State Management & Utils
  collection: ^1.19.1
  provider: ^6.1.5+1
  go_router: ^17.2.3
  intl: ^0.20.2
  meta: ^1.17.0
  rxdart: ^0.28.0

  # UI & Assets
  cupertino_icons: ^1.0.9
  google_fonts: ^8.1.0
  fl_chart: ^1.2.0
  font_awesome_flutter: ^11.0.0

  # Device & Services
  android_alarm_manager_plus: ^5.0.0
  connectivity_plus: ^7.1.1
  device_info_plus: ^13.1.0
  flutter_local_notifications: ^21.0.0
  flutter_timezone: ^5.0.2
  package_info_plus: ^10.1.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  google_mobile_ads: ^8.0.0

  # Local Database
  sqflite: ^2.4.2+1
  path: ^1.9.1
  sqflite_common_ffi: ^2.4.0+3

  # Other
  jiffy: ^6.4.4
  timezone: ^0.11.0
  uuid: ^4.5.3
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  rename: ^3.1.0


  # Platform Interfaces
  connectivity_plus_platform_interface: ^2.1.0
  device_info_plus_platform_interface: ^8.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/image/ikon_apk.png"

flutter:
  uses-material-design: true
  assets:
    - assets/image/
