// Mocks generated by Mockito 5.4.6 from annotations
// in wifi/test/fitur/akun/page/daftar_akun_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter/material.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:riverpod_annotation/riverpod_annotation.dart' as _i4;
import 'package:shared_preferences/shared_preferences.dart' as _i3;
import 'package:state_notifier/state_notifier.dart' as _i8;
import 'package:wifi/fitur/akun/provider/akun_provider.dart' as _i2;
import 'package:wifi/fitur/pelanggan/core/user_activity_service.dart' as _i11;
import 'package:wifi/fitur/pelanggan/model/pelanggan_model.dart' as _i7;
import 'package:wifi/user/services/storage/layanan_penyimpanan_lokal.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAkunState_0 extends _i1.SmartFake implements _i2.AkunState {
  _FakeAkunState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSharedPreferences_1 extends _i1.SmartFake
    implements _i3.SharedPreferences {
  _FakeSharedPreferences_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PengelolaAkun].
///
/// See the documentation for Mockito's code generation for more information.
class MockPengelolaAkun extends _i1.Mock implements _i2.PengelolaAkun {
  MockPengelolaAkun() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Ref get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _i5.dummyValue<_i4.Ref>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i4.Ref);

  @override
  _i4.AsyncValue<_i2.AkunState> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i5.dummyValue<_i4.AsyncValue<_i2.AkunState>>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.AsyncValue<_i2.AkunState>);

  @override
  set state(_i4.AsyncValue<_i2.AkunState>? newState) => super.noSuchMethod(
        Invocation.setter(
          #state,
          newState,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i2.AkunState> get future => (super.noSuchMethod(
        Invocation.getter(#future),
        returnValue: _i6.Future<_i2.AkunState>.value(_FakeAkunState_0(
          this,
          Invocation.getter(#future),
        )),
      ) as _i6.Future<_i2.AkunState>);

  @override
  _i6.Future<_i2.AkunState> build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _i6.Future<_i2.AkunState>.value(_FakeAkunState_0(
          this,
          Invocation.method(
            #build,
            [],
          ),
        )),
      ) as _i6.Future<_i2.AkunState>);

  @override
  _i6.Future<void> login(_i7.PelangganModel? akun) => (super.noSuchMethod(
        Invocation.method(
          #login,
          [akun],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> hapusAkun(String? id) => (super.noSuchMethod(
        Invocation.method(
          #hapusAkun,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> hapusTokenLogin() => (super.noSuchMethod(
        Invocation.method(
          #hapusTokenLogin,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i8.RemoveListener listenSelf(
    void Function(
      _i4.AsyncValue<_i2.AkunState>?,
      _i4.AsyncValue<_i2.AkunState>,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValue: () {},
      ) as _i8.RemoveListener);

  @override
  bool updateShouldNotify(
    _i4.AsyncValue<_i2.AkunState>? previous,
    _i4.AsyncValue<_i2.AkunState>? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<_i2.AkunState> update(
    _i6.FutureOr<_i2.AkunState> Function(_i2.AkunState)? cb, {
    _i6.FutureOr<_i2.AkunState> Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [cb],
          {#onError: onError},
        ),
        returnValue: _i6.Future<_i2.AkunState>.value(_FakeAkunState_0(
          this,
          Invocation.method(
            #update,
            [cb],
            {#onError: onError},
          ),
        )),
      ) as _i6.Future<_i2.AkunState>);
}

/// A class which mocks [LayananPenyimpananLokal].
///
/// See the documentation for Mockito's code generation for more information.
class MockLayananPenyimpananLokal extends _i1.Mock
    implements _i9.LayananPenyimpananLokal {
  MockLayananPenyimpananLokal() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SharedPreferences get prefs => (super.noSuchMethod(
        Invocation.getter(#prefs),
        returnValue: _FakeSharedPreferences_1(
          this,
          Invocation.getter(#prefs),
        ),
      ) as _i3.SharedPreferences);

  @override
  _i6.Future<void> simpanModeTema(_i10.ThemeMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #simpanModeTema,
          [mode],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i10.ThemeMode> ambilModeTema() => (super.noSuchMethod(
        Invocation.method(
          #ambilModeTema,
          [],
        ),
        returnValue: _i6.Future<_i10.ThemeMode>.value(_i10.ThemeMode.system),
      ) as _i6.Future<_i10.ThemeMode>);

  @override
  _i6.Future<void> simpanAkun(_i7.PelangganModel? pelanggan) =>
      (super.noSuchMethod(
        Invocation.method(
          #simpanAkun,
          [pelanggan],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> simpanAkunSaatIni(_i7.PelangganModel? pelanggan) =>
      (super.noSuchMethod(
        Invocation.method(
          #simpanAkunSaatIni,
          [pelanggan],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i7.PelangganModel>> ambilDaftarAkun() => (super.noSuchMethod(
        Invocation.method(
          #ambilDaftarAkun,
          [],
        ),
        returnValue:
            _i6.Future<List<_i7.PelangganModel>>.value(<_i7.PelangganModel>[]),
      ) as _i6.Future<List<_i7.PelangganModel>>);

  @override
  _i6.Future<void> hapusAkun(String? idPengguna) => (super.noSuchMethod(
        Invocation.method(
          #hapusAkun,
          [idPengguna],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> hapusAkunSaatIni() => (super.noSuchMethod(
        Invocation.method(
          #hapusAkunSaatIni,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> hapusTokenLogin() => (super.noSuchMethod(
        Invocation.method(
          #hapusTokenLogin,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i7.PelangganModel?> ambilAkunLogin() => (super.noSuchMethod(
        Invocation.method(
          #ambilAkunLogin,
          [],
        ),
        returnValue: _i6.Future<_i7.PelangganModel?>.value(),
      ) as _i6.Future<_i7.PelangganModel?>);

  @override
  _i6.Future<void> hapusSemuaData() => (super.noSuchMethod(
        Invocation.method(
          #hapusSemuaData,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [UserActivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserActivityService extends _i1.Mock
    implements _i11.UserActivityService {
  MockUserActivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> pingActivity(
    String? customerId, {
    bool? force = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pingActivity,
          [customerId],
          {#force: force},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i10.NavigatorObserver {
  MockNavigatorObserver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void didPush(
    _i10.Route<dynamic>? route,
    _i10.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didPush,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didPop(
    _i10.Route<dynamic>? route,
    _i10.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didPop,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i10.Route<dynamic>? route,
    _i10.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didRemove,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didReplace({
    _i10.Route<dynamic>? newRoute,
    _i10.Route<dynamic>? oldRoute,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #didReplace,
          [],
          {
            #newRoute: newRoute,
            #oldRoute: oldRoute,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeTop(
    _i10.Route<dynamic>? topRoute,
    _i10.Route<dynamic>? previousTopRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didChangeTop,
          [
            topRoute,
            previousTopRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didStartUserGesture(
    _i10.Route<dynamic>? route,
    _i10.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didStartUserGesture,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didStopUserGesture() => super.noSuchMethod(
        Invocation.method(
          #didStopUserGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
