// Mocks generated by Mockito 5.4.6 from annotations
// in wifi/test/fitur/speedtest/provider/uji_kecepatan_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter/foundation.dart' as _i3;
import 'package:flutter/src/widgets/framework.dart' as _i2;
import 'package:flutter/src/widgets/notification_listener.dart' as _i7;
import 'package:flutter_speed_test_plus/src/flutter_speed_test_plus.dart'
    as _i4;
import 'package:flutter_speed_test_plus/src/flutter_speed_test_plus_platform_interface.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWidget_0 extends _i1.SmartFake implements _i2.Widget {
  _FakeWidget_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeInheritedWidget_1 extends _i1.SmartFake
    implements _i2.InheritedWidget {
  _FakeInheritedWidget_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDiagnosticsNode_2 extends _i1.SmartFake
    implements _i3.DiagnosticsNode {
  _FakeDiagnosticsNode_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({
    _i3.TextTreeConfiguration? parentConfiguration,
    _i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info,
  }) =>
      super.toString();
}

/// A class which mocks [FlutterInternetSpeedTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterInternetSpeedTest extends _i1.Mock
    implements _i4.FlutterInternetSpeedTest {
  MockFlutterInternetSpeedTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLogEnabled => (super.noSuchMethod(
        Invocation.getter(#isLogEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool isTestInProgress() => (super.noSuchMethod(
        Invocation.method(
          #isTestInProgress,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> startTesting({
    required _i4.ResultCallback? onCompleted,
    _i4.DefaultCallback? onStarted,
    _i4.ResultCompletionCallback? onDownloadComplete,
    _i4.ResultCompletionCallback? onUploadComplete,
    _i4.TestProgressCallback? onProgress,
    _i4.DefaultCallback? onDefaultServerSelectionInProgress,
    _i4.DefaultServerSelectionCallback? onDefaultServerSelectionDone,
    _i6.ErrorCallback? onError,
    _i6.CancelCallback? onCancel,
    String? downloadTestServer,
    String? uploadTestServer,
    int? fileSizeInBytes = 10485760,
    bool? useFastApi = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startTesting,
          [],
          {
            #onCompleted: onCompleted,
            #onStarted: onStarted,
            #onDownloadComplete: onDownloadComplete,
            #onUploadComplete: onUploadComplete,
            #onProgress: onProgress,
            #onDefaultServerSelectionInProgress:
                onDefaultServerSelectionInProgress,
            #onDefaultServerSelectionDone: onDefaultServerSelectionDone,
            #onError: onError,
            #onCancel: onCancel,
            #downloadTestServer: downloadTestServer,
            #uploadTestServer: uploadTestServer,
            #fileSizeInBytes: fileSizeInBytes,
            #useFastApi: useFastApi,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void enableLog() => super.noSuchMethod(
        Invocation.method(
          #enableLog,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void disableLog() => super.noSuchMethod(
        Invocation.method(
          #disableLog,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<bool> cancelTest() => (super.noSuchMethod(
        Invocation.method(
          #cancelTest,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [BuildContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildContext extends _i1.Mock implements _i2.BuildContext {
  MockBuildContext() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Widget get widget => (super.noSuchMethod(
        Invocation.getter(#widget),
        returnValue: _FakeWidget_0(
          this,
          Invocation.getter(#widget),
        ),
      ) as _i2.Widget);

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  bool get debugDoingBuild => (super.noSuchMethod(
        Invocation.getter(#debugDoingBuild),
        returnValue: false,
      ) as bool);

  @override
  _i2.InheritedWidget dependOnInheritedElement(
    _i2.InheritedElement? ancestor, {
    Object? aspect,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dependOnInheritedElement,
          [ancestor],
          {#aspect: aspect},
        ),
        returnValue: _FakeInheritedWidget_1(
          this,
          Invocation.method(
            #dependOnInheritedElement,
            [ancestor],
            {#aspect: aspect},
          ),
        ),
      ) as _i2.InheritedWidget);

  @override
  void visitAncestorElements(_i2.ConditionalElementVisitor? visitor) =>
      super.noSuchMethod(
        Invocation.method(
          #visitAncestorElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void visitChildElements(_i2.ElementVisitor? visitor) => super.noSuchMethod(
        Invocation.method(
          #visitChildElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispatchNotification(_i7.Notification? notification) =>
      super.noSuchMethod(
        Invocation.method(
          #dispatchNotification,
          [notification],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.DiagnosticsNode describeElement(
    String? name, {
    _i3.DiagnosticsTreeStyle? style = _i3.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeElement,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeElement,
            [name],
            {#style: style},
          ),
        ),
      ) as _i3.DiagnosticsNode);

  @override
  _i3.DiagnosticsNode describeWidget(
    String? name, {
    _i3.DiagnosticsTreeStyle? style = _i3.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeWidget,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeWidget,
            [name],
            {#style: style},
          ),
        ),
      ) as _i3.DiagnosticsNode);

  @override
  List<_i3.DiagnosticsNode> describeMissingAncestor(
          {required Type? expectedAncestorType}) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeMissingAncestor,
          [],
          {#expectedAncestorType: expectedAncestorType},
        ),
        returnValue: <_i3.DiagnosticsNode>[],
      ) as List<_i3.DiagnosticsNode>);

  @override
  _i3.DiagnosticsNode describeOwnershipChain(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeOwnershipChain,
          [name],
        ),
        returnValue: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeOwnershipChain,
            [name],
          ),
        ),
      ) as _i3.DiagnosticsNode);
}
