// Mocks generated by Mockito 5.4.6 from annotations
// in wifi/test/admin/halaman/detail/detail_dompet_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter/src/widgets/navigator.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wifi/admin/data/sqlite.dart' as _i2;
import 'package:wifi/fitur/dompet/model/dompet_model.dart' as _i7;
import 'package:wifi/fitur/dompet/operasi/dompet_op_sqlite.dart' as _i5;
import 'package:wifi/fitur/paket/operasi/paket_op_sqlite.dart' as _i4;
import 'package:wifi/fitur/statistik/model/paket_terlaris_model.dart' as _i10;
import 'package:wifi/fitur/transaksi/model/transaksi_model.dart' as _i9;
import 'package:wifi/fitur/transaksi/operasi/transaksi_op_sqlite.dart' as _i8;
import 'package:wifi/shared/operasi/sqlite_operasi/base_op_sqlite.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSqliteDatabase_0 extends _i1.SmartFake
    implements _i2.SqliteDatabase {
  _FakeSqliteDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseOpSqlite_1 extends _i1.SmartFake implements _i3.BaseOpSqlite {
  _FakeBaseOpSqlite_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaketOpSqlite_2 extends _i1.SmartFake implements _i4.PaketOpSqlite {
  _FakePaketOpSqlite_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DompetOpSqlite].
///
/// See the documentation for Mockito's code generation for more information.
class MockDompetOpSqlite extends _i1.Mock implements _i5.DompetOpSqlite {
  MockDompetOpSqlite() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SqliteDatabase get sqliteDb =>
      (super.noSuchMethod(
            Invocation.getter(#sqliteDb),
            returnValue: _FakeSqliteDatabase_0(
              this,
              Invocation.getter(#sqliteDb),
            ),
          )
          as _i2.SqliteDatabase);

  @override
  _i6.Future<void> tambahDompet(
    _i7.DompetModel? dompet, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #tambahDompet,
              [dompet],
              {#dariServer: dariServer},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i7.DompetModel>> ambilSemua({
    bool? tampilkanYangDiarsip = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#ambilSemua, [], {
              #tampilkanYangDiarsip: tampilkanYangDiarsip,
            }),
            returnValue: _i6.Future<List<_i7.DompetModel>>.value(
              <_i7.DompetModel>[],
            ),
          )
          as _i6.Future<List<_i7.DompetModel>>);

  @override
  _i6.Future<_i7.DompetModel?> ambilBerdasarkanId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#ambilBerdasarkanId, [id]),
            returnValue: _i6.Future<_i7.DompetModel?>.value(),
          )
          as _i6.Future<_i7.DompetModel?>);

  @override
  _i6.Future<void> updateDompet(_i7.DompetModel? wallet) =>
      (super.noSuchMethod(
            Invocation.method(#updateDompet, [wallet]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> softDelete(String? id, {bool? dariServer = false}) =>
      (super.noSuchMethod(
            Invocation.method(#softDelete, [id], {#dariServer: dariServer}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> softDeleteAll({bool? dariServer = false}) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteAll, [], {#dariServer: dariServer}),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<double> ambilTotalsaldo() =>
      (super.noSuchMethod(
            Invocation.method(#ambilTotalsaldo, []),
            returnValue: _i6.Future<double>.value(0.0),
          )
          as _i6.Future<double>);

  @override
  _i6.Future<double> ambilSaldoPositif() =>
      (super.noSuchMethod(
            Invocation.method(#ambilSaldoPositif, []),
            returnValue: _i6.Future<double>.value(0.0),
          )
          as _i6.Future<double>);

  @override
  _i6.Future<double> ambilSaldoNegatif() =>
      (super.noSuchMethod(
            Invocation.method(#ambilSaldoNegatif, []),
            returnValue: _i6.Future<double>.value(0.0),
          )
          as _i6.Future<double>);

  @override
  _i6.Future<void> sisipkanAtauPerbaruiBatch(
    List<_i7.DompetModel>? daftarDompet, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sisipkanAtauPerbaruiBatch,
              [daftarDompet],
              {#dariServer: dariServer},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [TransaksiOpSqlite].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransaksiOpSqlite extends _i1.Mock implements _i8.TransaksiOpSqlite {
  MockTransaksiOpSqlite() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SqliteDatabase get sqliteDb =>
      (super.noSuchMethod(
            Invocation.getter(#sqliteDb),
            returnValue: _FakeSqliteDatabase_0(
              this,
              Invocation.getter(#sqliteDb),
            ),
          )
          as _i2.SqliteDatabase);

  @override
  _i3.BaseOpSqlite get baseOpSqlite =>
      (super.noSuchMethod(
            Invocation.getter(#baseOpSqlite),
            returnValue: _FakeBaseOpSqlite_1(
              this,
              Invocation.getter(#baseOpSqlite),
            ),
          )
          as _i3.BaseOpSqlite);

  @override
  _i4.PaketOpSqlite get paketOpsqlite =>
      (super.noSuchMethod(
            Invocation.getter(#paketOpsqlite),
            returnValue: _FakePaketOpSqlite_2(
              this,
              Invocation.getter(#paketOpsqlite),
            ),
          )
          as _i4.PaketOpSqlite);

  @override
  _i6.Future<int> tambahTransaksi(
    _i9.TransaksiModel? transaction, {
    bool? fromServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #tambahTransaksi,
              [transaction],
              {#fromServer: fromServer},
            ),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i9.TransaksiModel>> ambilSemua({
    bool? tampilkanYangDiarsip = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#ambilSemua, [], {
              #tampilkanYangDiarsip: tampilkanYangDiarsip,
            }),
            returnValue: _i6.Future<List<_i9.TransaksiModel>>.value(
              <_i9.TransaksiModel>[],
            ),
          )
          as _i6.Future<List<_i9.TransaksiModel>>);

  @override
  _i6.Future<void> perbaruiTransaksi(
    String? id,
    _i9.TransaksiModel? transaksi, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #perbaruiTransaksi,
              [id, transaksi],
              {#dariServer: dariServer},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i9.TransaksiModel?> ambilBerdasarkanId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#ambilBerdasarkanId, [id]),
            returnValue: _i6.Future<_i9.TransaksiModel?>.value(),
          )
          as _i6.Future<_i9.TransaksiModel?>);

  @override
  _i6.Future<List<_i9.TransaksiModel>> ambilBerdasarkanIdPelanggan(
    String? idPelanggan,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#ambilBerdasarkanIdPelanggan, [idPelanggan]),
            returnValue: _i6.Future<List<_i9.TransaksiModel>>.value(
              <_i9.TransaksiModel>[],
            ),
          )
          as _i6.Future<List<_i9.TransaksiModel>>);

  @override
  _i6.Future<List<_i9.TransaksiModel>> ambilBerdasarkanIdDompet(
    String? idDompet,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#ambilBerdasarkanIdDompet, [idDompet]),
            returnValue: _i6.Future<List<_i9.TransaksiModel>>.value(
              <_i9.TransaksiModel>[],
            ),
          )
          as _i6.Future<List<_i9.TransaksiModel>>);

  @override
  _i6.Future<List<_i9.TransaksiModel>> ambilBerdasarkanStatusAktivasi() =>
      (super.noSuchMethod(
            Invocation.method(#ambilBerdasarkanStatusAktivasi, []),
            returnValue: _i6.Future<List<_i9.TransaksiModel>>.value(
              <_i9.TransaksiModel>[],
            ),
          )
          as _i6.Future<List<_i9.TransaksiModel>>);

  @override
  _i6.Future<void> softDelete(String? id, {bool? dariServer = false}) =>
      (super.noSuchMethod(
            Invocation.method(#softDelete, [id], {#dariServer: dariServer}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> softDeleteAll({bool? dariServer = false}) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteAll, [], {#dariServer: dariServer}),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<double> ambilTotalPemasukan() =>
      (super.noSuchMethod(
            Invocation.method(#ambilTotalPemasukan, []),
            returnValue: _i6.Future<double>.value(0.0),
          )
          as _i6.Future<double>);

  @override
  _i6.Future<double> ambilTotalPengeluaran() =>
      (super.noSuchMethod(
            Invocation.method(#ambilTotalPengeluaran, []),
            returnValue: _i6.Future<double>.value(0.0),
          )
          as _i6.Future<double>);

  @override
  _i6.Future<double> getNetTotal() =>
      (super.noSuchMethod(
            Invocation.method(#getNetTotal, []),
            returnValue: _i6.Future<double>.value(0.0),
          )
          as _i6.Future<double>);

  @override
  _i6.Future<List<_i10.PaketTerlarisModel>> ambilPaketTerlaris({
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#ambilPaketTerlaris, [], {#limit: limit}),
            returnValue: _i6.Future<List<_i10.PaketTerlarisModel>>.value(
              <_i10.PaketTerlarisModel>[],
            ),
          )
          as _i6.Future<List<_i10.PaketTerlarisModel>>);

  @override
  _i6.Future<List<double>> ambilPendapatanHarian() =>
      (super.noSuchMethod(
            Invocation.method(#ambilPendapatanHarian, []),
            returnValue: _i6.Future<List<double>>.value(<double>[]),
          )
          as _i6.Future<List<double>>);

  @override
  _i6.Future<List<double>> ambilPendapatanMingguan() =>
      (super.noSuchMethod(
            Invocation.method(#ambilPendapatanMingguan, []),
            returnValue: _i6.Future<List<double>>.value(<double>[]),
          )
          as _i6.Future<List<double>>);

  @override
  _i6.Future<List<double>> ambilPendapatanBulanan() =>
      (super.noSuchMethod(
            Invocation.method(#ambilPendapatanBulanan, []),
            returnValue: _i6.Future<List<double>>.value(<double>[]),
          )
          as _i6.Future<List<double>>);

  @override
  _i6.Future<int> ambilPoinDidapat(String? idPelanggan) =>
      (super.noSuchMethod(
            Invocation.method(#ambilPoinDidapat, [idPelanggan]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> ambilPoinDigunakan(String? idPelanggan) =>
      (super.noSuchMethod(
            Invocation.method(#ambilPoinDigunakan, [idPelanggan]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> ambilTotalPoin(String? idPelanggan) =>
      (super.noSuchMethod(
            Invocation.method(#ambilTotalPoin, [idPelanggan]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> ambilTotalPoinSemuaPelanggan() =>
      (super.noSuchMethod(
            Invocation.method(#ambilTotalPoinSemuaPelanggan, []),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> sisipkanAtauPerbaruiBatch(
    List<_i9.TransaksiModel>? transaksi, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sisipkanAtauPerbaruiBatch,
              [transaksi],
              {#dariServer: dariServer},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<double> ambilTotalPendapatanPerbulan() =>
      (super.noSuchMethod(
            Invocation.method(#ambilTotalPendapatanPerbulan, []),
            returnValue: _i6.Future<double>.value(0.0),
          )
          as _i6.Future<double>);

  @override
  _i6.Future<List<_i9.TransaksiModel>> ambilBerdasarkanIds(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#ambilBerdasarkanIds, [ids]),
            returnValue: _i6.Future<List<_i9.TransaksiModel>>.value(
              <_i9.TransaksiModel>[],
            ),
          )
          as _i6.Future<List<_i9.TransaksiModel>>);
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i11.NavigatorObserver {
  MockNavigatorObserver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void didPush(
    _i11.Route<dynamic>? route,
    _i11.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didPush, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didPop(_i11.Route<dynamic>? route, _i11.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didPop, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i11.Route<dynamic>? route,
    _i11.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didRemove, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didReplace({
    _i11.Route<dynamic>? newRoute,
    _i11.Route<dynamic>? oldRoute,
  }) => super.noSuchMethod(
    Invocation.method(#didReplace, [], {
      #newRoute: newRoute,
      #oldRoute: oldRoute,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTop(
    _i11.Route<dynamic>? topRoute,
    _i11.Route<dynamic>? previousTopRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didChangeTop, [topRoute, previousTopRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStartUserGesture(
    _i11.Route<dynamic>? route,
    _i11.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didStartUserGesture, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStopUserGesture() => super.noSuchMethod(
    Invocation.method(#didStopUserGesture, []),
    returnValueForMissingStub: null,
  );
}
