// Mocks generated by Mockito 5.4.6 from annotations
// in wifi/test/shared/services/image_storage_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:convert' as _i8;
import 'dart:io' as _i4;
import 'dart:typed_data' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:storage_client/src/fetch.dart' as _i3;
import 'package:supabase/supabase.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFunctionsClient_0 extends _i1.SmartFake
    implements _i2.FunctionsClient {
  _FakeFunctionsClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseStorageClient_1 extends _i1.SmartFake
    implements _i2.SupabaseStorageClient {
  _FakeSupabaseStorageClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtimeClient_2 extends _i1.SmartFake
    implements _i2.RealtimeClient {
  _FakeRealtimeClient_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostgrestClient_3 extends _i1.SmartFake
    implements _i2.PostgrestClient {
  _FakePostgrestClient_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoTrueClient_4 extends _i1.SmartFake implements _i2.GoTrueClient {
  _FakeGoTrueClient_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseQueryBuilder_5 extends _i1.SmartFake
    implements _i2.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseQuerySchema_6 extends _i1.SmartFake
    implements _i2.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostgrestFilterBuilder_7<T1> extends _i1.SmartFake
    implements _i2.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtimeChannel_8 extends _i1.SmartFake
    implements _i2.RealtimeChannel {
  _FakeRealtimeChannel_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFetch_9 extends _i1.SmartFake implements _i3.Fetch {
  _FakeFetch_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageFileApi_10 extends _i1.SmartFake
    implements _i2.StorageFileApi {
  _FakeStorageFileApi_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBucket_11 extends _i1.SmartFake implements _i2.Bucket {
  _FakeBucket_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignedUploadURLResponse_12 extends _i1.SmartFake
    implements _i2.SignedUploadURLResponse {
  _FakeSignedUploadURLResponse_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileObjectV2_13 extends _i1.SmartFake implements _i2.FileObjectV2 {
  _FakeFileObjectV2_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFile_14 extends _i1.SmartFake implements _i4.File {
  _FakeFile_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUri_15 extends _i1.SmartFake implements Uri {
  _FakeUri_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDirectory_16 extends _i1.SmartFake implements _i4.Directory {
  _FakeDirectory_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileSystemEntity_17 extends _i1.SmartFake
    implements _i4.FileSystemEntity {
  _FakeFileSystemEntity_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_18 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRandomAccessFile_19 extends _i1.SmartFake
    implements _i4.RandomAccessFile {
  _FakeRandomAccessFile_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIOSink_20 extends _i1.SmartFake implements _i4.IOSink {
  _FakeIOSink_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileStat_21 extends _i1.SmartFake implements _i4.FileStat {
  _FakeFileStat_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i2.SupabaseClient {
  MockSupabaseClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FunctionsClient get functions => (super.noSuchMethod(
        Invocation.getter(#functions),
        returnValue: _FakeFunctionsClient_0(
          this,
          Invocation.getter(#functions),
        ),
      ) as _i2.FunctionsClient);

  @override
  _i2.SupabaseStorageClient get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeSupabaseStorageClient_1(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i2.SupabaseStorageClient);

  @override
  _i2.RealtimeClient get realtime => (super.noSuchMethod(
        Invocation.getter(#realtime),
        returnValue: _FakeRealtimeClient_2(
          this,
          Invocation.getter(#realtime),
        ),
      ) as _i2.RealtimeClient);

  @override
  _i2.PostgrestClient get rest => (super.noSuchMethod(
        Invocation.getter(#rest),
        returnValue: _FakePostgrestClient_3(
          this,
          Invocation.getter(#rest),
        ),
      ) as _i2.PostgrestClient);

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  _i2.GoTrueClient get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeGoTrueClient_4(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i2.GoTrueClient);

  @override
  set functions(_i2.FunctionsClient? value) => super.noSuchMethod(
        Invocation.setter(
          #functions,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set storage(_i2.SupabaseStorageClient? value) => super.noSuchMethod(
        Invocation.setter(
          #storage,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set realtime(_i2.RealtimeClient? value) => super.noSuchMethod(
        Invocation.setter(
          #realtime,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set rest(_i2.PostgrestClient? value) => super.noSuchMethod(
        Invocation.setter(
          #rest,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set headers(Map<String, String>? headers) => super.noSuchMethod(
        Invocation.setter(
          #headers,
          headers,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.SupabaseQueryBuilder from(String? table) => (super.noSuchMethod(
        Invocation.method(
          #from,
          [table],
        ),
        returnValue: _FakeSupabaseQueryBuilder_5(
          this,
          Invocation.method(
            #from,
            [table],
          ),
        ),
      ) as _i2.SupabaseQueryBuilder);

  @override
  _i2.SupabaseQuerySchema schema(String? schema) => (super.noSuchMethod(
        Invocation.method(
          #schema,
          [schema],
        ),
        returnValue: _FakeSupabaseQuerySchema_6(
          this,
          Invocation.method(
            #schema,
            [schema],
          ),
        ),
      ) as _i2.SupabaseQuerySchema);

  @override
  _i2.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rpc,
          [fn],
          {
            #params: params,
            #get: get,
          },
        ),
        returnValue: _FakePostgrestFilterBuilder_7<T>(
          this,
          Invocation.method(
            #rpc,
            [fn],
            {
              #params: params,
              #get: get,
            },
          ),
        ),
      ) as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.RealtimeChannel channel(
    String? name, {
    _i2.RealtimeChannelConfig? opts = const _i2.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #channel,
          [name],
          {#opts: opts},
        ),
        returnValue: _FakeRealtimeChannel_8(
          this,
          Invocation.method(
            #channel,
            [name],
            {#opts: opts},
          ),
        ),
      ) as _i2.RealtimeChannel);

  @override
  List<_i2.RealtimeChannel> getChannels() => (super.noSuchMethod(
        Invocation.method(
          #getChannels,
          [],
        ),
        returnValue: <_i2.RealtimeChannel>[],
      ) as List<_i2.RealtimeChannel>);

  @override
  _i5.Future<String> removeChannel(_i2.RealtimeChannel? channel) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeChannel,
          [channel],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #removeChannel,
            [channel],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<List<String>> removeAllChannels() => (super.noSuchMethod(
        Invocation.method(
          #removeAllChannels,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [SupabaseStorageClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseStorageClient extends _i1.Mock
    implements _i2.SupabaseStorageClient {
  MockSupabaseStorageClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get url => (super.noSuchMethod(
        Invocation.getter(#url),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#url),
        ),
      ) as String);

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  _i3.Fetch get storageFetch => (super.noSuchMethod(
        Invocation.getter(#storageFetch),
        returnValue: _FakeFetch_9(
          this,
          Invocation.getter(#storageFetch),
        ),
      ) as _i3.Fetch);

  @override
  set storageFetch(_i3.Fetch? value) => super.noSuchMethod(
        Invocation.setter(
          #storageFetch,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.StorageFileApi from(String? id) => (super.noSuchMethod(
        Invocation.method(
          #from,
          [id],
        ),
        returnValue: _FakeStorageFileApi_10(
          this,
          Invocation.method(
            #from,
            [id],
          ),
        ),
      ) as _i2.StorageFileApi);

  @override
  void setAuth(String? jwt) => super.noSuchMethod(
        Invocation.method(
          #setAuth,
          [jwt],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.SupabaseStorageClient setHeader(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setHeader,
          [
            key,
            value,
          ],
        ),
        returnValue: _FakeSupabaseStorageClient_1(
          this,
          Invocation.method(
            #setHeader,
            [
              key,
              value,
            ],
          ),
        ),
      ) as _i2.SupabaseStorageClient);

  @override
  _i5.Future<List<_i2.Bucket>> listBuckets() => (super.noSuchMethod(
        Invocation.method(
          #listBuckets,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Bucket>>.value(<_i2.Bucket>[]),
      ) as _i5.Future<List<_i2.Bucket>>);

  @override
  _i5.Future<_i2.Bucket> getBucket(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getBucket,
          [id],
        ),
        returnValue: _i5.Future<_i2.Bucket>.value(_FakeBucket_11(
          this,
          Invocation.method(
            #getBucket,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.Bucket>);

  @override
  _i5.Future<String> createBucket(
    String? id, [
    _i2.BucketOptions? bucketOptions = const _i2.BucketOptions(public: false),
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBucket,
          [
            id,
            bucketOptions,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #createBucket,
            [
              id,
              bucketOptions,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> updateBucket(
    String? id,
    _i2.BucketOptions? bucketOptions,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBucket,
          [
            id,
            bucketOptions,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #updateBucket,
            [
              id,
              bucketOptions,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> emptyBucket(String? id) => (super.noSuchMethod(
        Invocation.method(
          #emptyBucket,
          [id],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #emptyBucket,
            [id],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> deleteBucket(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteBucket,
          [id],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #deleteBucket,
            [id],
          ),
        )),
      ) as _i5.Future<String>);
}

/// A class which mocks [StorageFileApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageFileApi extends _i1.Mock implements _i2.StorageFileApi {
  MockStorageFileApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get url => (super.noSuchMethod(
        Invocation.getter(#url),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#url),
        ),
      ) as String);

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  _i2.StorageFileApi setHeader(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setHeader,
          [
            key,
            value,
          ],
        ),
        returnValue: _FakeStorageFileApi_10(
          this,
          Invocation.method(
            #setHeader,
            [
              key,
              value,
            ],
          ),
        ),
      ) as _i2.StorageFileApi);

  @override
  _i5.Future<String> upload(
    String? path,
    _i4.File? file, {
    _i2.FileOptions? fileOptions = const _i2.FileOptions(),
    int? retryAttempts,
    _i2.StorageRetryController? retryController,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upload,
          [
            path,
            file,
          ],
          {
            #fileOptions: fileOptions,
            #retryAttempts: retryAttempts,
            #retryController: retryController,
          },
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #upload,
            [
              path,
              file,
            ],
            {
              #fileOptions: fileOptions,
              #retryAttempts: retryAttempts,
              #retryController: retryController,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> uploadBinary(
    String? path,
    _i7.Uint8List? data, {
    _i2.FileOptions? fileOptions = const _i2.FileOptions(),
    int? retryAttempts,
    _i2.StorageRetryController? retryController,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadBinary,
          [
            path,
            data,
          ],
          {
            #fileOptions: fileOptions,
            #retryAttempts: retryAttempts,
            #retryController: retryController,
          },
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #uploadBinary,
            [
              path,
              data,
            ],
            {
              #fileOptions: fileOptions,
              #retryAttempts: retryAttempts,
              #retryController: retryController,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> uploadToSignedUrl(
    String? path,
    String? token,
    _i4.File? file, [
    _i2.FileOptions? fileOptions = const _i2.FileOptions(),
    int? retryAttempts,
    _i2.StorageRetryController? retryController,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadToSignedUrl,
          [
            path,
            token,
            file,
            fileOptions,
            retryAttempts,
            retryController,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #uploadToSignedUrl,
            [
              path,
              token,
              file,
              fileOptions,
              retryAttempts,
              retryController,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> uploadBinaryToSignedUrl(
    String? path,
    String? token,
    _i7.Uint8List? data, [
    _i2.FileOptions? fileOptions = const _i2.FileOptions(),
    int? retryAttempts,
    _i2.StorageRetryController? retryController,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadBinaryToSignedUrl,
          [
            path,
            token,
            data,
            fileOptions,
            retryAttempts,
            retryController,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #uploadBinaryToSignedUrl,
            [
              path,
              token,
              data,
              fileOptions,
              retryAttempts,
              retryController,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<_i2.SignedUploadURLResponse> createSignedUploadUrl(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSignedUploadUrl,
          [path],
        ),
        returnValue: _i5.Future<_i2.SignedUploadURLResponse>.value(
            _FakeSignedUploadURLResponse_12(
          this,
          Invocation.method(
            #createSignedUploadUrl,
            [path],
          ),
        )),
      ) as _i5.Future<_i2.SignedUploadURLResponse>);

  @override
  _i5.Future<String> update(
    String? path,
    _i4.File? file, {
    _i2.FileOptions? fileOptions = const _i2.FileOptions(),
    int? retryAttempts,
    _i2.StorageRetryController? retryController,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            path,
            file,
          ],
          {
            #fileOptions: fileOptions,
            #retryAttempts: retryAttempts,
            #retryController: retryController,
          },
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #update,
            [
              path,
              file,
            ],
            {
              #fileOptions: fileOptions,
              #retryAttempts: retryAttempts,
              #retryController: retryController,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> updateBinary(
    String? path,
    _i7.Uint8List? data, {
    _i2.FileOptions? fileOptions = const _i2.FileOptions(),
    int? retryAttempts,
    _i2.StorageRetryController? retryController,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBinary,
          [
            path,
            data,
          ],
          {
            #fileOptions: fileOptions,
            #retryAttempts: retryAttempts,
            #retryController: retryController,
          },
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #updateBinary,
            [
              path,
              data,
            ],
            {
              #fileOptions: fileOptions,
              #retryAttempts: retryAttempts,
              #retryController: retryController,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> move(
    String? fromPath,
    String? toPath, {
    String? destinationBucket,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #move,
          [
            fromPath,
            toPath,
          ],
          {#destinationBucket: destinationBucket},
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #move,
            [
              fromPath,
              toPath,
            ],
            {#destinationBucket: destinationBucket},
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> copy(
    String? fromPath,
    String? toPath, {
    String? destinationBucket,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copy,
          [
            fromPath,
            toPath,
          ],
          {#destinationBucket: destinationBucket},
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #copy,
            [
              fromPath,
              toPath,
            ],
            {#destinationBucket: destinationBucket},
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> createSignedUrl(
    String? path,
    int? expiresIn, {
    _i2.TransformOptions? transform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSignedUrl,
          [
            path,
            expiresIn,
          ],
          {#transform: transform},
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #createSignedUrl,
            [
              path,
              expiresIn,
            ],
            {#transform: transform},
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<List<_i2.SignedUrl>> createSignedUrls(
    List<String>? paths,
    int? expiresIn,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSignedUrls,
          [
            paths,
            expiresIn,
          ],
        ),
        returnValue: _i5.Future<List<_i2.SignedUrl>>.value(<_i2.SignedUrl>[]),
      ) as _i5.Future<List<_i2.SignedUrl>>);

  @override
  _i5.Future<_i7.Uint8List> download(
    String? path, {
    _i2.TransformOptions? transform,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [path],
          {
            #transform: transform,
            #queryParams: queryParams,
          },
        ),
        returnValue: _i5.Future<_i7.Uint8List>.value(_i7.Uint8List(0)),
      ) as _i5.Future<_i7.Uint8List>);

  @override
  _i5.Future<_i2.FileObjectV2> info(String? path) => (super.noSuchMethod(
        Invocation.method(
          #info,
          [path],
        ),
        returnValue: _i5.Future<_i2.FileObjectV2>.value(_FakeFileObjectV2_13(
          this,
          Invocation.method(
            #info,
            [path],
          ),
        )),
      ) as _i5.Future<_i2.FileObjectV2>);

  @override
  _i5.Future<bool> exists(String? path) => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [path],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  String getPublicUrl(
    String? path, {
    _i2.TransformOptions? transform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPublicUrl,
          [path],
          {#transform: transform},
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getPublicUrl,
            [path],
            {#transform: transform},
          ),
        ),
      ) as String);

  @override
  _i5.Future<List<_i2.FileObject>> remove(List<String>? paths) =>
      (super.noSuchMethod(
        Invocation.method(
          #remove,
          [paths],
        ),
        returnValue: _i5.Future<List<_i2.FileObject>>.value(<_i2.FileObject>[]),
      ) as _i5.Future<List<_i2.FileObject>>);

  @override
  _i5.Future<List<_i2.FileObject>> list({
    String? path,
    _i2.SearchOptions? searchOptions = const _i2.SearchOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #list,
          [],
          {
            #path: path,
            #searchOptions: searchOptions,
          },
        ),
        returnValue: _i5.Future<List<_i2.FileObject>>.value(<_i2.FileObject>[]),
      ) as _i5.Future<List<_i2.FileObject>>);
}

/// A class which mocks [File].
///
/// See the documentation for Mockito's code generation for more information.
class MockFile extends _i1.Mock implements _i4.File {
  MockFile() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.File get absolute => (super.noSuchMethod(
        Invocation.getter(#absolute),
        returnValue: _FakeFile_14(
          this,
          Invocation.getter(#absolute),
        ),
      ) as _i4.File);

  @override
  String get path => (super.noSuchMethod(
        Invocation.getter(#path),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#path),
        ),
      ) as String);

  @override
  Uri get uri => (super.noSuchMethod(
        Invocation.getter(#uri),
        returnValue: _FakeUri_15(
          this,
          Invocation.getter(#uri),
        ),
      ) as Uri);

  @override
  bool get isAbsolute => (super.noSuchMethod(
        Invocation.getter(#isAbsolute),
        returnValue: false,
      ) as bool);

  @override
  _i4.Directory get parent => (super.noSuchMethod(
        Invocation.getter(#parent),
        returnValue: _FakeDirectory_16(
          this,
          Invocation.getter(#parent),
        ),
      ) as _i4.Directory);

  @override
  _i5.Future<_i4.File> create({
    bool? recursive = false,
    bool? exclusive = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
          {
            #recursive: recursive,
            #exclusive: exclusive,
          },
        ),
        returnValue: _i5.Future<_i4.File>.value(_FakeFile_14(
          this,
          Invocation.method(
            #create,
            [],
            {
              #recursive: recursive,
              #exclusive: exclusive,
            },
          ),
        )),
      ) as _i5.Future<_i4.File>);

  @override
  void createSync({
    bool? recursive = false,
    bool? exclusive = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #createSync,
          [],
          {
            #recursive: recursive,
            #exclusive: exclusive,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i4.File> rename(String? newPath) => (super.noSuchMethod(
        Invocation.method(
          #rename,
          [newPath],
        ),
        returnValue: _i5.Future<_i4.File>.value(_FakeFile_14(
          this,
          Invocation.method(
            #rename,
            [newPath],
          ),
        )),
      ) as _i5.Future<_i4.File>);

  @override
  _i4.File renameSync(String? newPath) => (super.noSuchMethod(
        Invocation.method(
          #renameSync,
          [newPath],
        ),
        returnValue: _FakeFile_14(
          this,
          Invocation.method(
            #renameSync,
            [newPath],
          ),
        ),
      ) as _i4.File);

  @override
  _i5.Future<_i4.FileSystemEntity> delete({bool? recursive = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {#recursive: recursive},
        ),
        returnValue:
            _i5.Future<_i4.FileSystemEntity>.value(_FakeFileSystemEntity_17(
          this,
          Invocation.method(
            #delete,
            [],
            {#recursive: recursive},
          ),
        )),
      ) as _i5.Future<_i4.FileSystemEntity>);

  @override
  void deleteSync({bool? recursive = false}) => super.noSuchMethod(
        Invocation.method(
          #deleteSync,
          [],
          {#recursive: recursive},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i4.File> copy(String? newPath) => (super.noSuchMethod(
        Invocation.method(
          #copy,
          [newPath],
        ),
        returnValue: _i5.Future<_i4.File>.value(_FakeFile_14(
          this,
          Invocation.method(
            #copy,
            [newPath],
          ),
        )),
      ) as _i5.Future<_i4.File>);

  @override
  _i4.File copySync(String? newPath) => (super.noSuchMethod(
        Invocation.method(
          #copySync,
          [newPath],
        ),
        returnValue: _FakeFile_14(
          this,
          Invocation.method(
            #copySync,
            [newPath],
          ),
        ),
      ) as _i4.File);

  @override
  _i5.Future<int> length() => (super.noSuchMethod(
        Invocation.method(
          #length,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  int lengthSync() => (super.noSuchMethod(
        Invocation.method(
          #lengthSync,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i5.Future<DateTime> lastAccessed() => (super.noSuchMethod(
        Invocation.method(
          #lastAccessed,
          [],
        ),
        returnValue: _i5.Future<DateTime>.value(_FakeDateTime_18(
          this,
          Invocation.method(
            #lastAccessed,
            [],
          ),
        )),
      ) as _i5.Future<DateTime>);

  @override
  DateTime lastAccessedSync() => (super.noSuchMethod(
        Invocation.method(
          #lastAccessedSync,
          [],
        ),
        returnValue: _FakeDateTime_18(
          this,
          Invocation.method(
            #lastAccessedSync,
            [],
          ),
        ),
      ) as DateTime);

  @override
  _i5.Future<dynamic> setLastAccessed(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #setLastAccessed,
          [time],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  void setLastAccessedSync(DateTime? time) => super.noSuchMethod(
        Invocation.method(
          #setLastAccessedSync,
          [time],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<DateTime> lastModified() => (super.noSuchMethod(
        Invocation.method(
          #lastModified,
          [],
        ),
        returnValue: _i5.Future<DateTime>.value(_FakeDateTime_18(
          this,
          Invocation.method(
            #lastModified,
            [],
          ),
        )),
      ) as _i5.Future<DateTime>);

  @override
  DateTime lastModifiedSync() => (super.noSuchMethod(
        Invocation.method(
          #lastModifiedSync,
          [],
        ),
        returnValue: _FakeDateTime_18(
          this,
          Invocation.method(
            #lastModifiedSync,
            [],
          ),
        ),
      ) as DateTime);

  @override
  _i5.Future<dynamic> setLastModified(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #setLastModified,
          [time],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  void setLastModifiedSync(DateTime? time) => super.noSuchMethod(
        Invocation.method(
          #setLastModifiedSync,
          [time],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i4.RandomAccessFile> open(
          {_i4.FileMode? mode = _i4.FileMode.read}) =>
      (super.noSuchMethod(
        Invocation.method(
          #open,
          [],
          {#mode: mode},
        ),
        returnValue:
            _i5.Future<_i4.RandomAccessFile>.value(_FakeRandomAccessFile_19(
          this,
          Invocation.method(
            #open,
            [],
            {#mode: mode},
          ),
        )),
      ) as _i5.Future<_i4.RandomAccessFile>);

  @override
  _i4.RandomAccessFile openSync({_i4.FileMode? mode = _i4.FileMode.read}) =>
      (super.noSuchMethod(
        Invocation.method(
          #openSync,
          [],
          {#mode: mode},
        ),
        returnValue: _FakeRandomAccessFile_19(
          this,
          Invocation.method(
            #openSync,
            [],
            {#mode: mode},
          ),
        ),
      ) as _i4.RandomAccessFile);

  @override
  _i5.Stream<List<int>> openRead([
    int? start,
    int? end,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #openRead,
          [
            start,
            end,
          ],
        ),
        returnValue: _i5.Stream<List<int>>.empty(),
      ) as _i5.Stream<List<int>>);

  @override
  _i4.IOSink openWrite({
    _i4.FileMode? mode = _i4.FileMode.write,
    _i8.Encoding? encoding = const _i8.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #openWrite,
          [],
          {
            #mode: mode,
            #encoding: encoding,
          },
        ),
        returnValue: _FakeIOSink_20(
          this,
          Invocation.method(
            #openWrite,
            [],
            {
              #mode: mode,
              #encoding: encoding,
            },
          ),
        ),
      ) as _i4.IOSink);

  @override
  _i5.Future<_i7.Uint8List> readAsBytes() => (super.noSuchMethod(
        Invocation.method(
          #readAsBytes,
          [],
        ),
        returnValue: _i5.Future<_i7.Uint8List>.value(_i7.Uint8List(0)),
      ) as _i5.Future<_i7.Uint8List>);

  @override
  _i7.Uint8List readAsBytesSync() => (super.noSuchMethod(
        Invocation.method(
          #readAsBytesSync,
          [],
        ),
        returnValue: _i7.Uint8List(0),
      ) as _i7.Uint8List);

  @override
  _i5.Future<String> readAsString(
          {_i8.Encoding? encoding = const _i8.Utf8Codec()}) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAsString,
          [],
          {#encoding: encoding},
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #readAsString,
            [],
            {#encoding: encoding},
          ),
        )),
      ) as _i5.Future<String>);

  @override
  String readAsStringSync({_i8.Encoding? encoding = const _i8.Utf8Codec()}) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAsStringSync,
          [],
          {#encoding: encoding},
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #readAsStringSync,
            [],
            {#encoding: encoding},
          ),
        ),
      ) as String);

  @override
  _i5.Future<List<String>> readAsLines(
          {_i8.Encoding? encoding = const _i8.Utf8Codec()}) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAsLines,
          [],
          {#encoding: encoding},
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  List<String> readAsLinesSync(
          {_i8.Encoding? encoding = const _i8.Utf8Codec()}) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAsLinesSync,
          [],
          {#encoding: encoding},
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i5.Future<_i4.File> writeAsBytes(
    List<int>? bytes, {
    _i4.FileMode? mode = _i4.FileMode.write,
    bool? flush = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeAsBytes,
          [bytes],
          {
            #mode: mode,
            #flush: flush,
          },
        ),
        returnValue: _i5.Future<_i4.File>.value(_FakeFile_14(
          this,
          Invocation.method(
            #writeAsBytes,
            [bytes],
            {
              #mode: mode,
              #flush: flush,
            },
          ),
        )),
      ) as _i5.Future<_i4.File>);

  @override
  void writeAsBytesSync(
    List<int>? bytes, {
    _i4.FileMode? mode = _i4.FileMode.write,
    bool? flush = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #writeAsBytesSync,
          [bytes],
          {
            #mode: mode,
            #flush: flush,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i4.File> writeAsString(
    String? contents, {
    _i4.FileMode? mode = _i4.FileMode.write,
    _i8.Encoding? encoding = const _i8.Utf8Codec(),
    bool? flush = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeAsString,
          [contents],
          {
            #mode: mode,
            #encoding: encoding,
            #flush: flush,
          },
        ),
        returnValue: _i5.Future<_i4.File>.value(_FakeFile_14(
          this,
          Invocation.method(
            #writeAsString,
            [contents],
            {
              #mode: mode,
              #encoding: encoding,
              #flush: flush,
            },
          ),
        )),
      ) as _i5.Future<_i4.File>);

  @override
  void writeAsStringSync(
    String? contents, {
    _i4.FileMode? mode = _i4.FileMode.write,
    _i8.Encoding? encoding = const _i8.Utf8Codec(),
    bool? flush = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #writeAsStringSync,
          [contents],
          {
            #mode: mode,
            #encoding: encoding,
            #flush: flush,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<bool> exists() => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  bool existsSync() => (super.noSuchMethod(
        Invocation.method(
          #existsSync,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<String> resolveSymbolicLinks() => (super.noSuchMethod(
        Invocation.method(
          #resolveSymbolicLinks,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #resolveSymbolicLinks,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  String resolveSymbolicLinksSync() => (super.noSuchMethod(
        Invocation.method(
          #resolveSymbolicLinksSync,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #resolveSymbolicLinksSync,
            [],
          ),
        ),
      ) as String);

  @override
  _i5.Future<_i4.FileStat> stat() => (super.noSuchMethod(
        Invocation.method(
          #stat,
          [],
        ),
        returnValue: _i5.Future<_i4.FileStat>.value(_FakeFileStat_21(
          this,
          Invocation.method(
            #stat,
            [],
          ),
        )),
      ) as _i5.Future<_i4.FileStat>);

  @override
  _i4.FileStat statSync() => (super.noSuchMethod(
        Invocation.method(
          #statSync,
          [],
        ),
        returnValue: _FakeFileStat_21(
          this,
          Invocation.method(
            #statSync,
            [],
          ),
        ),
      ) as _i4.FileStat);

  @override
  _i5.Stream<_i4.FileSystemEvent> watch({
    int? events = 15,
    bool? recursive = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watch,
          [],
          {
            #events: events,
            #recursive: recursive,
          },
        ),
        returnValue: _i5.Stream<_i4.FileSystemEvent>.empty(),
      ) as _i5.Stream<_i4.FileSystemEvent>);
}
