// Mocks generated by Mockito 5.4.6 from annotations
// in wifi/test/shared/services/user_activity_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wifi/fitur/pelanggan/model/pelanggan_model.dart' as _i4;
import 'package:wifi/shared/operasi/firebase_operasi/customer_op_firebase.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CustomerOpFirebase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerOpFirebase extends _i1.Mock
    implements _i2.CustomerOpFirebase {
  MockCustomerOpFirebase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addPelanggan(_i4.PelangganModel? pelanggan) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPelanggan,
          [pelanggan],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updatePelanggan(_i4.PelangganModel? pelanggan) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePelanggan,
          [pelanggan],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> softDelete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #softDelete,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> hapusPelangganPermanen(String? idPelanggan) =>
      (super.noSuchMethod(
        Invocation.method(
          #hapusPelangganPermanen,
          [idPelanggan],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> perbaruiTerakhirAktif(String? id) => (super.noSuchMethod(
        Invocation.method(
          #perbaruiTerakhirAktif,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> simpanTokenFCM(
    String? id,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #simpanTokenFCM,
          [
            id,
            token,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.PelangganModel>> getAllPelanggan() => (super.noSuchMethod(
        Invocation.method(
          #getAllPelanggan,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.PelangganModel>>.value(<_i4.PelangganModel>[]),
      ) as _i3.Future<List<_i4.PelangganModel>>);

  @override
  _i3.Stream<_i4.PelangganModel?> getStreamPelanggan(String? idPengguna) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStreamPelanggan,
          [idPengguna],
        ),
        returnValue: _i3.Stream<_i4.PelangganModel?>.empty(),
      ) as _i3.Stream<_i4.PelangganModel?>);

  @override
  _i3.Future<_i4.PelangganModel?> getById(String? idPengguna) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [idPengguna],
        ),
        returnValue: _i3.Future<_i4.PelangganModel?>.value(),
      ) as _i3.Future<_i4.PelangganModel?>);
}
