// Mocks generated by Mockito 5.4.6 from annotations
// in wifi/test/admin/providers/active_customer_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wifi/admin/data/sqlite.dart' as _i2;
import 'package:wifi/shared/export/model.dart' as _i3;
import 'package:wifi/shared/model/active_customer_detail_model.dart' as _i6;
import 'package:wifi/shared/operasi/sqlite_operasi/active_customer_operation.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabaseHelper_0 extends _i1.SmartFake
    implements _i2.SqliteDatabase {
  _FakeDatabaseHelper_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeActiveCustomerModel_1 extends _i1.SmartFake
    implements _i3.ActiveCustomerModel {
  _FakeActiveCustomerModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ActiveCustomerOperation].
///
/// See the documentation for Mockito's code generation for more information.
class MockActiveCustomerOperation extends _i1.Mock
    implements _i4.ActiveCustomerOperation {
  @override
  _i2.SqliteDatabase get dbHelper => (super.noSuchMethod(
        Invocation.getter(#dbHelper),
        returnValue: _FakeDatabaseHelper_0(
          this,
          Invocation.getter(#dbHelper),
        ),
        returnValueForMissingStub: _FakeDatabaseHelper_0(
          this,
          Invocation.getter(#dbHelper),
        ),
      ) as _i2.SqliteDatabase);

  @override
  _i5.Future<void> rescheduleAllNotifications() => (super.noSuchMethod(
        Invocation.method(
          #rescheduleAllNotifications,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.ActiveCustomerDetailModel>>
      getAllActiveCustomersWithDetails() => (super.noSuchMethod(
            Invocation.method(
              #getAllActiveCustomersWithDetails,
              [],
            ),
            returnValue: _i5.Future<List<_i6.ActiveCustomerDetailModel>>.value(
                <_i6.ActiveCustomerDetailModel>[]),
            returnValueForMissingStub:
                _i5.Future<List<_i6.ActiveCustomerDetailModel>>.value(
                    <_i6.ActiveCustomerDetailModel>[]),
          ) as _i5.Future<List<_i6.ActiveCustomerDetailModel>>);

  @override
  _i5.Future<_i3.ActiveCustomerModel> createActiveCustomer(
    _i3.ActiveCustomerModel? activeCustomer, {
    bool? fromServer = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createActiveCustomer,
          [activeCustomer],
          {#fromServer: fromServer},
        ),
        returnValue: _i5.Future<_i3.ActiveCustomerModel>.value(
            _FakeActiveCustomerModel_1(
          this,
          Invocation.method(
            #createActiveCustomer,
            [activeCustomer],
            {#fromServer: fromServer},
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.ActiveCustomerModel>.value(
            _FakeActiveCustomerModel_1(
          this,
          Invocation.method(
            #createActiveCustomer,
            [activeCustomer],
            {#fromServer: fromServer},
          ),
        )),
      ) as _i5.Future<_i3.ActiveCustomerModel>);

  @override
  _i5.Future<List<_i3.ActiveCustomerModel>> getAllActiveCustomers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllActiveCustomers,
          [],
        ),
        returnValue: _i5.Future<List<_i3.ActiveCustomerModel>>.value(
            <_i3.ActiveCustomerModel>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i3.ActiveCustomerModel>>.value(
                <_i3.ActiveCustomerModel>[]),
      ) as _i5.Future<List<_i3.ActiveCustomerModel>>);

  @override
  _i5.Future<_i3.ActiveCustomerModel?> getActiveCustomerById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveCustomerById,
          [id],
        ),
        returnValue: _i5.Future<_i3.ActiveCustomerModel?>.value(),
        returnValueForMissingStub: _i5.Future<_i3.ActiveCustomerModel?>.value(),
      ) as _i5.Future<_i3.ActiveCustomerModel?>);

  @override
  _i5.Future<_i3.ActiveCustomerModel> updateActiveCustomer(
    _i3.ActiveCustomerModel? activeCustomer, {
    bool? fromServer = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateActiveCustomer,
          [activeCustomer],
          {#fromServer: fromServer},
        ),
        returnValue: _i5.Future<_i3.ActiveCustomerModel>.value(
            _FakeActiveCustomerModel_1(
          this,
          Invocation.method(
            #updateActiveCustomer,
            [activeCustomer],
            {#fromServer: fromServer},
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.ActiveCustomerModel>.value(
            _FakeActiveCustomerModel_1(
          this,
          Invocation.method(
            #updateActiveCustomer,
            [activeCustomer],
            {#fromServer: fromServer},
          ),
        )),
      ) as _i5.Future<_i3.ActiveCustomerModel>);

  @override
  _i5.Future<void> scheduleNotification(
          _i3.ActiveCustomerModel? activeCustomer) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleNotification,
          [activeCustomer],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> insertOrUpdateBatch(
    List<_i3.ActiveCustomerModel>? items, {
    bool? fromServer = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertOrUpdateBatch,
          [items],
          {#fromServer: fromServer},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> softDelete(
    String? id, {
    bool? fromServer = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #softDelete,
          [id],
          {#fromServer: fromServer},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> permanentlyDeleteArchivedCustomers(
          {bool? fromServer = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #permanentlyDeleteArchivedCustomers,
          [],
          {#fromServer: fromServer},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> archiveExpiredCustomers({bool? fromServer = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #archiveExpiredCustomers,
          [],
          {#fromServer: fromServer},
        ),
        returnValue: _i5.Future<int>.value(0),
        returnValueForMissingStub: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> softDeleteAll({bool? fromServer = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #softDeleteAll,
          [],
          {#fromServer: fromServer},
        ),
        returnValue: _i5.Future<int>.value(0),
        returnValueForMissingStub: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.ActiveCustomerModel>> ambilBerdasarkanIds(
          List<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveCustomersByIds,
          [ids],
        ),
        returnValue: _i5.Future<List<_i3.ActiveCustomerModel>>.value(
            <_i3.ActiveCustomerModel>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i3.ActiveCustomerModel>>.value(
                <_i3.ActiveCustomerModel>[]),
      ) as _i5.Future<List<_i3.ActiveCustomerModel>>);
}
