// Mocks generated by Mockito 5.4.6 from annotations
// in wifi/test/admin/providers/detail_langganan_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wifi/admin/data/sqlite.dart' as _i2;
import 'package:wifi/fitur/paket/model/paket_model.dart' as _i8;
import 'package:wifi/fitur/paket/operasi/paket_op_sqlite.dart' as _i4;
import 'package:wifi/fitur/pelanggan/model/pelanggan_model.dart' as _i7;
import 'package:wifi/fitur/pelanggan/operasi/pelanggan_op_sqlite.dart' as _i5;
import 'package:wifi/fitur/statistik/model/paket_terlaris_model.dart' as _i11;
import 'package:wifi/fitur/transaksi/model/transaksi_model.dart' as _i10;
import 'package:wifi/fitur/transaksi/operasi/transaksi_op_sqlite.dart' as _i9;
import 'package:wifi/shared/operasi/sqlite_operasi/base_op_sqlite.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSqliteDatabase_0 extends _i1.SmartFake
    implements _i2.SqliteDatabase {
  _FakeSqliteDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseOpSqlite_1 extends _i1.SmartFake implements _i3.BaseOpSqlite {
  _FakeBaseOpSqlite_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaketOpSqlite_2 extends _i1.SmartFake implements _i4.PaketOpSqlite {
  _FakePaketOpSqlite_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PelangganOpSqlite].
///
/// See the documentation for Mockito's code generation for more information.
class MockPelangganOpSqlite extends _i1.Mock implements _i5.PelangganOpSqlite {
  MockPelangganOpSqlite() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SqliteDatabase get sqliteDb =>
      (super.noSuchMethod(
            Invocation.getter(#sqliteDb),
            returnValue: _FakeSqliteDatabase_0(
              this,
              Invocation.getter(#sqliteDb),
            ),
          )
          as _i2.SqliteDatabase);

  @override
  _i6.Future<void> tambahPelanggan(
    _i7.PelangganModel? pelanggan, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #tambahPelanggan,
              [pelanggan],
              {#dariServer: dariServer},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i7.PelangganModel>> ambilSemua({
    bool? tampilkanYangDiarsip = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#ambilSemua, [], {
              #tampilkanYangDiarsip: tampilkanYangDiarsip,
            }),
            returnValue: _i6.Future<List<_i7.PelangganModel>>.value(
              <_i7.PelangganModel>[],
            ),
          )
          as _i6.Future<List<_i7.PelangganModel>>);

  @override
  _i6.Future<_i7.PelangganModel?> ambilBerdasarkanId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#ambilBerdasarkanId, [id]),
            returnValue: _i6.Future<_i7.PelangganModel?>.value(),
          )
          as _i6.Future<_i7.PelangganModel?>);

  @override
  _i6.Future<void> perbaruiPelanggan(
    _i7.PelangganModel? pelanggan, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #perbaruiPelanggan,
              [pelanggan],
              {#dariServer: dariServer},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> softDelete(String? id, {bool? dariServer = false}) =>
      (super.noSuchMethod(
            Invocation.method(#softDelete, [id], {#dariServer: dariServer}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> softDeleteSemua({bool? dariServer = false}) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteSemua, [], {#dariServer: dariServer}),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i7.PelangganModel>> ambilPerubahanSejak(DateTime? sejak) =>
      (super.noSuchMethod(
            Invocation.method(#ambilPerubahanSejak, [sejak]),
            returnValue: _i6.Future<List<_i7.PelangganModel>>.value(
              <_i7.PelangganModel>[],
            ),
          )
          as _i6.Future<List<_i7.PelangganModel>>);

  @override
  _i6.Future<void> sisipkanAtauPerbaruiBatch(
    List<_i7.PelangganModel>? pelanggan, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sisipkanAtauPerbaruiBatch,
              [pelanggan],
              {#dariServer: dariServer},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i7.PelangganModel>> ambilPelangganBerdasarkanId(
    List<String>? ids,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#ambilPelangganBerdasarkanId, [ids]),
            returnValue: _i6.Future<List<_i7.PelangganModel>>.value(
              <_i7.PelangganModel>[],
            ),
          )
          as _i6.Future<List<_i7.PelangganModel>>);
}

/// A class which mocks [PaketOpSqlite].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaketOpSqlite extends _i1.Mock implements _i4.PaketOpSqlite {
  MockPaketOpSqlite() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SqliteDatabase get sqliteDb =>
      (super.noSuchMethod(
            Invocation.getter(#sqliteDb),
            returnValue: _FakeSqliteDatabase_0(
              this,
              Invocation.getter(#sqliteDb),
            ),
          )
          as _i2.SqliteDatabase);

  @override
  _i3.BaseOpSqlite get basOpSqlite =>
      (super.noSuchMethod(
            Invocation.getter(#basOpSqlite),
            returnValue: _FakeBaseOpSqlite_1(
              this,
              Invocation.getter(#basOpSqlite),
            ),
          )
          as _i3.BaseOpSqlite);

  @override
  _i6.Future<void> tambahPaket(
    _i8.PaketModel? paket, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#tambahPaket, [paket], {#dariServer: dariServer}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i8.PaketModel>> ambilSemua({
    bool? tampilkanYangDiarsip = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#ambilSemua, [], {
              #tampilkanYangDiarsip: tampilkanYangDiarsip,
            }),
            returnValue: _i6.Future<List<_i8.PaketModel>>.value(
              <_i8.PaketModel>[],
            ),
          )
          as _i6.Future<List<_i8.PaketModel>>);

  @override
  _i6.Future<List<_i8.PaketModel>> ambilPaketPublik() =>
      (super.noSuchMethod(
            Invocation.method(#ambilPaketPublik, []),
            returnValue: _i6.Future<List<_i8.PaketModel>>.value(
              <_i8.PaketModel>[],
            ),
          )
          as _i6.Future<List<_i8.PaketModel>>);

  @override
  _i6.Future<_i8.PaketModel?> ambilBerdasarkanId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#ambilBerdasarkanId, [id]),
            returnValue: _i6.Future<_i8.PaketModel?>.value(),
          )
          as _i6.Future<_i8.PaketModel?>);

  @override
  _i6.Future<void> perbaruiPaket(
    _i8.PaketModel? paket, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #perbaruiPaket,
              [paket],
              {#dariServer: dariServer},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> hapusSementara(String? id, {bool? dariServer = false}) =>
      (super.noSuchMethod(
            Invocation.method(#hapusSementara, [id], {#dariServer: dariServer}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> hapusSementaraSemua({bool? dariServer = false}) =>
      (super.noSuchMethod(
            Invocation.method(#hapusSementaraSemua, [], {
              #dariServer: dariServer,
            }),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> hapusSemua({bool? dariServer = false}) =>
      (super.noSuchMethod(
            Invocation.method(#hapusSemua, [], {#dariServer: dariServer}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i8.PaketModel>> ambilPerubahanSejak(DateTime? since) =>
      (super.noSuchMethod(
            Invocation.method(#ambilPerubahanSejak, [since]),
            returnValue: _i6.Future<List<_i8.PaketModel>>.value(
              <_i8.PaketModel>[],
            ),
          )
          as _i6.Future<List<_i8.PaketModel>>);

  @override
  _i6.Future<void> sisipkanAtauPerbaruiBatch(
    List<_i8.PaketModel>? items, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sisipkanAtauPerbaruiBatch,
              [items],
              {#dariServer: dariServer},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i8.PaketModel>> ambilBerdasarkanBeberapaId(
    List<String>? ids,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#ambilBerdasarkanBeberapaId, [ids]),
            returnValue: _i6.Future<List<_i8.PaketModel>>.value(
              <_i8.PaketModel>[],
            ),
          )
          as _i6.Future<List<_i8.PaketModel>>);
}

/// A class which mocks [TransaksiOpSqlite].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransaksiOpSqlite extends _i1.Mock implements _i9.TransaksiOpSqlite {
  MockTransaksiOpSqlite() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SqliteDatabase get sqliteDb =>
      (super.noSuchMethod(
            Invocation.getter(#sqliteDb),
            returnValue: _FakeSqliteDatabase_0(
              this,
              Invocation.getter(#sqliteDb),
            ),
          )
          as _i2.SqliteDatabase);

  @override
  _i3.BaseOpSqlite get baseOpSqlite =>
      (super.noSuchMethod(
            Invocation.getter(#baseOpSqlite),
            returnValue: _FakeBaseOpSqlite_1(
              this,
              Invocation.getter(#baseOpSqlite),
            ),
          )
          as _i3.BaseOpSqlite);

  @override
  _i4.PaketOpSqlite get paketOpsqlite =>
      (super.noSuchMethod(
            Invocation.getter(#paketOpsqlite),
            returnValue: _FakePaketOpSqlite_2(
              this,
              Invocation.getter(#paketOpsqlite),
            ),
          )
          as _i4.PaketOpSqlite);

  @override
  _i6.Future<int> tambahTransaksi(
    _i10.TransaksiModel? transaction, {
    bool? fromServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #tambahTransaksi,
              [transaction],
              {#fromServer: fromServer},
            ),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i10.TransaksiModel>> ambilSemua({
    bool? tampilkanYangDiarsip = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#ambilSemua, [], {
              #tampilkanYangDiarsip: tampilkanYangDiarsip,
            }),
            returnValue: _i6.Future<List<_i10.TransaksiModel>>.value(
              <_i10.TransaksiModel>[],
            ),
          )
          as _i6.Future<List<_i10.TransaksiModel>>);

  @override
  _i6.Future<_i10.TransaksiModel?> ambilBerdasarkanId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#ambilBerdasarkanId, [id]),
            returnValue: _i6.Future<_i10.TransaksiModel?>.value(),
          )
          as _i6.Future<_i10.TransaksiModel?>);

  @override
  _i6.Future<List<_i10.TransaksiModel>> ambilBerdasarkanIdPelanggan(
    String? idPelanggan,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#ambilBerdasarkanIdPelanggan, [idPelanggan]),
            returnValue: _i6.Future<List<_i10.TransaksiModel>>.value(
              <_i10.TransaksiModel>[],
            ),
          )
          as _i6.Future<List<_i10.TransaksiModel>>);

  @override
  _i6.Future<List<_i10.TransaksiModel>> ambilBerdasarkanIdDompet(
    String? idDompet,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#ambilBerdasarkanIdDompet, [idDompet]),
            returnValue: _i6.Future<List<_i10.TransaksiModel>>.value(
              <_i10.TransaksiModel>[],
            ),
          )
          as _i6.Future<List<_i10.TransaksiModel>>);

  @override
  _i6.Future<List<_i10.TransaksiModel>> ambilBerdasarkanStatusAktivasi() =>
      (super.noSuchMethod(
            Invocation.method(#ambilBerdasarkanStatusAktivasi, []),
            returnValue: _i6.Future<List<_i10.TransaksiModel>>.value(
              <_i10.TransaksiModel>[],
            ),
          )
          as _i6.Future<List<_i10.TransaksiModel>>);

  @override
  _i6.Future<void> perbaruiTransaksi(
    String? id,
    _i10.TransaksiModel? transaksi, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #perbaruiTransaksi,
              [id, transaksi],
              {#dariServer: dariServer},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> softDelete(String? id, {bool? dariServer = false}) =>
      (super.noSuchMethod(
            Invocation.method(#softDelete, [id], {#dariServer: dariServer}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> softDeleteAll({bool? dariServer = false}) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteAll, [], {#dariServer: dariServer}),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<double> getTotalIncome() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalIncome, []),
            returnValue: _i6.Future<double>.value(0.0),
          )
          as _i6.Future<double>);

  @override
  _i6.Future<double> getTotalExpense() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalExpense, []),
            returnValue: _i6.Future<double>.value(0.0),
          )
          as _i6.Future<double>);

  @override
  _i6.Future<double> getNetTotal() =>
      (super.noSuchMethod(
            Invocation.method(#getNetTotal, []),
            returnValue: _i6.Future<double>.value(0.0),
          )
          as _i6.Future<double>);

  @override
  _i6.Future<List<_i11.PaketTerlarisModel>> ambilPaketTerlaris({
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#ambilPaketTerlaris, [], {#limit: limit}),
            returnValue: _i6.Future<List<_i11.PaketTerlarisModel>>.value(
              <_i11.PaketTerlarisModel>[],
            ),
          )
          as _i6.Future<List<_i11.PaketTerlarisModel>>);

  @override
  _i6.Future<List<double>> ambilPendapatanHarian() =>
      (super.noSuchMethod(
            Invocation.method(#ambilPendapatanHarian, []),
            returnValue: _i6.Future<List<double>>.value(<double>[]),
          )
          as _i6.Future<List<double>>);

  @override
  _i6.Future<List<double>> ambilPendapatanMingguan() =>
      (super.noSuchMethod(
            Invocation.method(#ambilPendapatanMingguan, []),
            returnValue: _i6.Future<List<double>>.value(<double>[]),
          )
          as _i6.Future<List<double>>);

  @override
  _i6.Future<List<double>> ambilPendapatanBulanan() =>
      (super.noSuchMethod(
            Invocation.method(#ambilPendapatanBulanan, []),
            returnValue: _i6.Future<List<double>>.value(<double>[]),
          )
          as _i6.Future<List<double>>);

  @override
  _i6.Future<int> ambilPoinDidapat(String? idPelanggan) =>
      (super.noSuchMethod(
            Invocation.method(#ambilPoinDidapat, [idPelanggan]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> ambilPoinDigunakan(String? idPelanggan) =>
      (super.noSuchMethod(
            Invocation.method(#ambilPoinDigunakan, [idPelanggan]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> ambilTotalPoin(String? idPelanggan) =>
      (super.noSuchMethod(
            Invocation.method(#ambilTotalPoin, [idPelanggan]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> ambilTotalPoinSemuaPelanggan() =>
      (super.noSuchMethod(
            Invocation.method(#ambilTotalPoinSemuaPelanggan, []),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> sisipkanAtauPerbaruiBatch(
    List<_i10.TransaksiModel>? transaksi, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sisipkanAtauPerbaruiBatch,
              [transaksi],
              {#dariServer: dariServer},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<double> ambilTotalPendapatanPerbulan() =>
      (super.noSuchMethod(
            Invocation.method(#ambilTotalPendapatanPerbulan, []),
            returnValue: _i6.Future<double>.value(0.0),
          )
          as _i6.Future<double>);

  @override
  _i6.Future<List<_i10.TransaksiModel>> ambilBerdasarkanIds(
    List<String>? ids,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#ambilBerdasarkanIds, [ids]),
            returnValue: _i6.Future<List<_i10.TransaksiModel>>.value(
              <_i10.TransaksiModel>[],
            ),
          )
          as _i6.Future<List<_i10.TransaksiModel>>);
}
