// Mocks generated by Mockito 5.4.6 from annotations
// in wifi/test/admin/providers/wallet_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wifi/admin/data/sqlite.dart' as _i2;
import 'package:wifi/fitur/dompet/model/dompet_model.dart' as _i5;
import 'package:wifi/fitur/dompet/operasi/dompet_op_sqlite.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSqliteDatabase_0 extends _i1.SmartFake
    implements _i2.SqliteDatabase {
  _FakeSqliteDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DompetOpSqlite].
///
/// See the documentation for Mockito's code generation for more information.
class MockDompetOpSqlite extends _i1.Mock implements _i3.DompetOpSqlite {
  @override
  _i2.SqliteDatabase get sqliteDb => (super.noSuchMethod(
        Invocation.getter(#sqliteDb),
        returnValue: _FakeSqliteDatabase_0(
          this,
          Invocation.getter(#sqliteDb),
        ),
        returnValueForMissingStub: _FakeSqliteDatabase_0(
          this,
          Invocation.getter(#sqliteDb),
        ),
      ) as _i2.SqliteDatabase);

  @override
  _i4.Future<void> tambahDompet(
    _i5.DompetModel? wallet, {
    bool? fromServer = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #tambahDompet,
          [wallet],
          {#fromServer: fromServer},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.DompetModel>> ambilSemua({bool? showArchived = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #ambilSemua,
          [],
          {#showArchived: showArchived},
        ),
        returnValue:
            _i4.Future<List<_i5.DompetModel>>.value(<_i5.DompetModel>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.DompetModel>>.value(<_i5.DompetModel>[]),
      ) as _i4.Future<List<_i5.DompetModel>>);

  @override
  _i4.Future<_i5.DompetModel?> ambilBerdasarkanId(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #ambilBerdasarkanId,
          [id],
        ),
        returnValue: _i4.Future<_i5.DompetModel?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.DompetModel?>.value(),
      ) as _i4.Future<_i5.DompetModel?>);

  @override
  _i4.Future<void> updateDompet(
    _i5.DompetModel? wallet, {
    bool? fromServer = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDompet,
          [wallet],
          {#fromServer: fromServer},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> softDelete(
    String? id, {
    bool? fromServer = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #softDelete,
          [id],
          {#fromServer: fromServer},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> softDeleteAll({bool? fromServer = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #softDeleteAll,
          [],
          {#fromServer: fromServer},
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<double> ambilTotalsaldo() => (super.noSuchMethod(
        Invocation.method(
          #ambilTotalsaldo,
          [],
        ),
        returnValue: _i4.Future<double>.value(0.0),
        returnValueForMissingStub: _i4.Future<double>.value(0.0),
      ) as _i4.Future<double>);

  @override
  _i4.Future<double> ambilSaldoPositif() => (super.noSuchMethod(
        Invocation.method(
          #ambilSaldoPositif,
          [],
        ),
        returnValue: _i4.Future<double>.value(0.0),
        returnValueForMissingStub: _i4.Future<double>.value(0.0),
      ) as _i4.Future<double>);

  @override
  _i4.Future<double> ambilSaldoNegatif() => (super.noSuchMethod(
        Invocation.method(
          #ambilSaldoNegatif,
          [],
        ),
        returnValue: _i4.Future<double>.value(0.0),
        returnValueForMissingStub: _i4.Future<double>.value(0.0),
      ) as _i4.Future<double>);

  @override
  _i4.Future<void> insertOrUpdateBatch(
    List<_i5.DompetModel>? items, {
    bool? fromServer = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertOrUpdateBatch,
          [items],
          {#fromServer: fromServer},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
