// Mocks generated by Mockito 5.4.6 from annotations
// in wifi/test/admin/providers/wallet_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wifi/admin/data/sqlite.dart' as _i2;
import 'package:wifi/shared/model/wallet_model.dart' as _i5;
import 'package:wifi/shared/operasi/sqlite_operasi/wallet_operation.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabaseHelper_0 extends _i1.SmartFake
    implements _i2.DatabaseHelper {
  _FakeDatabaseHelper_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WalletOperation].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletOperation extends _i1.Mock implements _i3.WalletOperation {
  @override
  _i2.DatabaseHelper get dbHelper => (super.noSuchMethod(
        Invocation.getter(#dbHelper),
        returnValue: _FakeDatabaseHelper_0(
          this,
          Invocation.getter(#dbHelper),
        ),
        returnValueForMissingStub: _FakeDatabaseHelper_0(
          this,
          Invocation.getter(#dbHelper),
        ),
      ) as _i2.DatabaseHelper);

  @override
  _i4.Future<void> createWallet(
    _i5.WalletModel? wallet, {
    bool? fromServer = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createWallet,
          [wallet],
          {#fromServer: fromServer},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.WalletModel>> getWallets({bool? showArchived = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWallets,
          [],
          {#showArchived: showArchived},
        ),
        returnValue:
            _i4.Future<List<_i5.WalletModel>>.value(<_i5.WalletModel>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.WalletModel>>.value(<_i5.WalletModel>[]),
      ) as _i4.Future<List<_i5.WalletModel>>);

  @override
  _i4.Future<_i5.WalletModel?> getWalletById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getWalletById,
          [id],
        ),
        returnValue: _i4.Future<_i5.WalletModel?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.WalletModel?>.value(),
      ) as _i4.Future<_i5.WalletModel?>);

  @override
  _i4.Future<void> updateWallet(
    _i5.WalletModel? wallet, {
    bool? fromServer = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWallet,
          [wallet],
          {#fromServer: fromServer},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAllWallets({bool? fromServer = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllWallets,
          [],
          {#fromServer: fromServer},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> softDelete(
    String? id, {
    bool? fromServer = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #softDelete,
          [id],
          {#fromServer: fromServer},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> softDeleteAll({bool? fromServer = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #softDeleteAll,
          [],
          {#fromServer: fromServer},
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<double> getTotalBalance() => (super.noSuchMethod(
        Invocation.method(
          #getTotalBalance,
          [],
        ),
        returnValue: _i4.Future<double>.value(0.0),
        returnValueForMissingStub: _i4.Future<double>.value(0.0),
      ) as _i4.Future<double>);

  @override
  _i4.Future<double> getPositiveBalance() => (super.noSuchMethod(
        Invocation.method(
          #getPositiveBalance,
          [],
        ),
        returnValue: _i4.Future<double>.value(0.0),
        returnValueForMissingStub: _i4.Future<double>.value(0.0),
      ) as _i4.Future<double>);

  @override
  _i4.Future<double> getNegativeBalance() => (super.noSuchMethod(
        Invocation.method(
          #getNegativeBalance,
          [],
        ),
        returnValue: _i4.Future<double>.value(0.0),
        returnValueForMissingStub: _i4.Future<double>.value(0.0),
      ) as _i4.Future<double>);

  @override
  _i4.Future<void> insertOrUpdateBatch(
    List<_i5.WalletModel>? items, {
    bool? fromServer = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertOrUpdateBatch,
          [items],
          {#fromServer: fromServer},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
