// Mocks generated by Mockito 5.4.6 from annotations
// in wifi/test/fitur/pelanggan/page/user/detail_pelanggan_u_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wifi/fitur/pelanggan/model/pelanggan_model.dart' as _i5;
import 'package:wifi/fitur/pelanggan/operasi/pelanggan_op_firebase.dart' as _i3;
import 'package:wifi/fitur/transaksi/model/transaksi_model.dart' as _i7;
import 'package:wifi/fitur/transaksi/operasi/transaksi_op_firebase.dart' as _i6;
import 'package:wifi/user/widget/ads/interstitial/layanan_iklan_interstisial.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFirebaseFirestore_0 extends _i1.SmartFake
    implements _i2.FirebaseFirestore {
  _FakeFirebaseFirestore_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocumentReference_1<T extends Object?> extends _i1.SmartFake
    implements _i2.DocumentReference<T> {
  _FakeDocumentReference_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PelangganOpFirebase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPelangganOpFirebase extends _i1.Mock
    implements _i3.PelangganOpFirebase {
  MockPelangganOpFirebase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> tambahPelanggan(_i5.PelangganModel? pelanggan) =>
      (super.noSuchMethod(
            Invocation.method(#tambahPelanggan, [pelanggan]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> perbaruiPelanggan(_i5.PelangganModel? pelanggan) =>
      (super.noSuchMethod(
            Invocation.method(#perbaruiPelanggan, [pelanggan]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> softDelete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDelete, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> perbaruiTerakhirAktif(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#perbaruiTerakhirAktif, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> simpanTokenFCM(String? id, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#simpanTokenFCM, [id, token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.PelangganModel>> ambilSemuaPelanggan() =>
      (super.noSuchMethod(
            Invocation.method(#ambilSemuaPelanggan, []),
            returnValue: _i4.Future<List<_i5.PelangganModel>>.value(
              <_i5.PelangganModel>[],
            ),
          )
          as _i4.Future<List<_i5.PelangganModel>>);

  @override
  _i4.Stream<_i5.PelangganModel?> ambilStreamBerdasarkanId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#ambilStreamBerdasarkanId, [id]),
            returnValue: _i4.Stream<_i5.PelangganModel?>.empty(),
          )
          as _i4.Stream<_i5.PelangganModel?>);

  @override
  _i4.Future<_i5.PelangganModel?> ambilBerdasarkanId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#ambilBerdasarkanId, [id]),
            returnValue: _i4.Future<_i5.PelangganModel?>.value(),
          )
          as _i4.Future<_i5.PelangganModel?>);
}

/// A class which mocks [TransaksiOpFirebase].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransaksiOpFirebase extends _i1.Mock
    implements _i6.TransaksiOpFirebase {
  MockTransaksiOpFirebase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseFirestore get firestore =>
      (super.noSuchMethod(
            Invocation.getter(#firestore),
            returnValue: _FakeFirebaseFirestore_0(
              this,
              Invocation.getter(#firestore),
            ),
          )
          as _i2.FirebaseFirestore);

  @override
  _i4.Future<void> tambahTransaksi(_i7.TransaksiModel? transaksi) =>
      (super.noSuchMethod(
            Invocation.method(#tambahTransaksi, [transaksi]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i7.TransaksiModel?>
  ambilTransaksiLunasTerbaruBerdasarkanIdPelanggan(String? idPelanggan) =>
      (super.noSuchMethod(
            Invocation.method(
              #ambilTransaksiLunasTerbaruBerdasarkanIdPelanggan,
              [idPelanggan],
            ),
            returnValue: _i4.Future<_i7.TransaksiModel?>.value(),
          )
          as _i4.Future<_i7.TransaksiModel?>);

  @override
  _i4.Future<List<_i7.TransaksiModel>> ambilBelumLunasBerdasarkanIdPelanggan(
    String? idPelanggan,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#ambilBelumLunasBerdasarkanIdPelanggan, [
              idPelanggan,
            ]),
            returnValue: _i4.Future<List<_i7.TransaksiModel>>.value(
              <_i7.TransaksiModel>[],
            ),
          )
          as _i4.Future<List<_i7.TransaksiModel>>);

  @override
  _i4.Future<List<_i7.TransaksiModel>> ambilBerdasarkanIdPelanggan(
    String? idPelanggan,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#ambilBerdasarkanIdPelanggan, [idPelanggan]),
            returnValue: _i4.Future<List<_i7.TransaksiModel>>.value(
              <_i7.TransaksiModel>[],
            ),
          )
          as _i4.Future<List<_i7.TransaksiModel>>);

  @override
  _i4.Future<int> ambilTotalPoin(String? idPelanggan) =>
      (super.noSuchMethod(
            Invocation.method(#ambilTotalPoin, [idPelanggan]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> softDeleteTransaksi(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteTransaksi, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.TransaksiModel>> ambilPaketAktifPelanggan(
    String? idPelanggan,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#ambilPaketAktifPelanggan, [idPelanggan]),
            returnValue: _i4.Future<List<_i7.TransaksiModel>>.value(
              <_i7.TransaksiModel>[],
            ),
          )
          as _i4.Future<List<_i7.TransaksiModel>>);

  @override
  _i4.Future<_i2.DocumentReference<Object?>> tambah(
    String? collectionName,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#tambah, [collectionName, data]),
            returnValue: _i4.Future<_i2.DocumentReference<Object?>>.value(
              _FakeDocumentReference_1<Object?>(
                this,
                Invocation.method(#tambah, [collectionName, data]),
              ),
            ),
          )
          as _i4.Future<_i2.DocumentReference<Object?>>);

  @override
  _i4.Future<void> sisipkan(
    String? collectionName,
    String? docId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sisipkan, [collectionName, docId, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> update(
    String? collectionName,
    String? docId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [collectionName, docId, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> softDelete(String? collectionName, String? docId) =>
      (super.noSuchMethod(
            Invocation.method(#softDelete, [collectionName, docId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> hapusPermanen(String? collectionName, String? docId) =>
      (super.noSuchMethod(
            Invocation.method(#hapusPermanen, [collectionName, docId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> hapusSementaraSemua(String? collectionName) =>
      (super.noSuchMethod(
            Invocation.method(#hapusSementaraSemua, [collectionName]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> insertOrUpdateBatch(
    String? collectionName,
    List<Map<String, dynamic>>? items,
    String? idKey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertOrUpdateBatch, [
              collectionName,
              items,
              idKey,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [LayananIklanInterstisial].
///
/// See the documentation for Mockito's code generation for more information.
class MockLayananIklanInterstisial extends _i1.Mock
    implements _i8.LayananIklanInterstisial {
  MockLayananIklanInterstisial() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> preloadAd() =>
      (super.noSuchMethod(
            Invocation.method(#preloadAd, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> show() =>
      (super.noSuchMethod(
            Invocation.method(#show, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
