// Mocks generated by Mockito 5.4.6 from annotations
// in wifi/test/admin/app_admin_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wifi/admin/data/sqlite.dart' as _i2;
import 'package:wifi/fitur/pelanggan_aktif/model/detail_pelanggan_aktif_model.dart'
    as _i7;
import 'package:wifi/fitur/pelanggan_aktif/model/pelanggan_aktif_model.dart'
    as _i3;
import 'package:wifi/fitur/pelanggan_aktif/operasi/pelanggan_aktif_op_sqlite.dart'
    as _i6;
import 'package:wifi/fitur/sinkronisasi/layanan_unduhan_awal.dart' as _i4;
import 'package:wifi/shared/services/koneksi_internet_service.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSqliteDatabase_0 extends _i1.SmartFake
    implements _i2.SqliteDatabase {
  _FakeSqliteDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePelangganAktifModel_1 extends _i1.SmartFake
    implements _i3.PelangganAktifModel {
  _FakePelangganAktifModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LayananUnduhanAwal].
///
/// See the documentation for Mockito's code generation for more information.
class MockLayananUnduhanAwal extends _i1.Mock
    implements _i4.LayananUnduhanAwal {
  MockLayananUnduhanAwal() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> jalankanUnduhanAwal() =>
      (super.noSuchMethod(
            Invocation.method(#jalankanUnduhanAwal, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [PelangganAktifOpSqlite].
///
/// See the documentation for Mockito's code generation for more information.
class MockPelangganAktifOpSqlite extends _i1.Mock
    implements _i6.PelangganAktifOpSqlite {
  MockPelangganAktifOpSqlite() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SqliteDatabase get sqliteDb =>
      (super.noSuchMethod(
            Invocation.getter(#sqliteDb),
            returnValue: _FakeSqliteDatabase_0(
              this,
              Invocation.getter(#sqliteDb),
            ),
          )
          as _i2.SqliteDatabase);

  @override
  _i5.Future<void> jadwalkanUlangSemuaNotifikasi() =>
      (super.noSuchMethod(
            Invocation.method(#jadwalkanUlangSemuaNotifikasi, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.DetailPelangganAktifModel>>
  ambilSemuaPelangganAktifDenganDetail() =>
      (super.noSuchMethod(
            Invocation.method(#ambilSemuaPelangganAktifDenganDetail, []),
            returnValue: _i5.Future<List<_i7.DetailPelangganAktifModel>>.value(
              <_i7.DetailPelangganAktifModel>[],
            ),
          )
          as _i5.Future<List<_i7.DetailPelangganAktifModel>>);

  @override
  _i5.Future<_i3.PelangganAktifModel> tambahPelangganAktif(
    _i3.PelangganAktifModel? pelangganAktif, {
    bool? fromServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #tambahPelangganAktif,
              [pelangganAktif],
              {#fromServer: fromServer},
            ),
            returnValue: _i5.Future<_i3.PelangganAktifModel>.value(
              _FakePelangganAktifModel_1(
                this,
                Invocation.method(
                  #tambahPelangganAktif,
                  [pelangganAktif],
                  {#fromServer: fromServer},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.PelangganAktifModel>);

  @override
  _i5.Future<List<_i3.PelangganAktifModel>> ambilSemua() =>
      (super.noSuchMethod(
            Invocation.method(#ambilSemua, []),
            returnValue: _i5.Future<List<_i3.PelangganAktifModel>>.value(
              <_i3.PelangganAktifModel>[],
            ),
          )
          as _i5.Future<List<_i3.PelangganAktifModel>>);

  @override
  _i5.Future<_i3.PelangganAktifModel?> ambilBerdasarkanid(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#ambilBerdasarkanid, [id]),
            returnValue: _i5.Future<_i3.PelangganAktifModel?>.value(),
          )
          as _i5.Future<_i3.PelangganAktifModel?>);

  @override
  _i5.Future<_i3.PelangganAktifModel> updatePelangganAktif(
    _i3.PelangganAktifModel? pelangganAktif, {
    bool? fromServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updatePelangganAktif,
              [pelangganAktif],
              {#fromServer: fromServer},
            ),
            returnValue: _i5.Future<_i3.PelangganAktifModel>.value(
              _FakePelangganAktifModel_1(
                this,
                Invocation.method(
                  #updatePelangganAktif,
                  [pelangganAktif],
                  {#fromServer: fromServer},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.PelangganAktifModel>);

  @override
  _i5.Future<void> jadwalkanNotifikasi(
    _i3.PelangganAktifModel? pelangganAktif,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#jadwalkanNotifikasi, [pelangganAktif]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> sisipkanAtauPerbaruiBatch(
    List<_i3.PelangganAktifModel>? daftarPelangganAktif, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sisipkanAtauPerbaruiBatch,
              [daftarPelangganAktif],
              {#dariServer: dariServer},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> softDelete(String? id, {bool? dariServer = false}) =>
      (super.noSuchMethod(
            Invocation.method(#softDelete, [id], {#dariServer: dariServer}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> softDeletePelangganAktifDanTransaksi(
    String? idPelangganAKtif,
    String? idTransaksi, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #softDeletePelangganAktifDanTransaksi,
              [idPelangganAKtif, idTransaksi],
              {#dariServer: dariServer},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> arsipkanLanggananKadaluarsa({bool? dariServer = false}) =>
      (super.noSuchMethod(
            Invocation.method(#arsipkanLanggananKadaluarsa, [], {
              #dariServer: dariServer,
            }),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> softDeleteAll({bool? dariServer = false}) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteAll, [], {#dariServer: dariServer}),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.PelangganAktifModel>> ambilBerdasarkanIds(
    List<String>? ids,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#ambilBerdasarkanIds, [ids]),
            returnValue: _i5.Future<List<_i3.PelangganAktifModel>>.value(
              <_i3.PelangganAktifModel>[],
            ),
          )
          as _i5.Future<List<_i3.PelangganAktifModel>>);
}

/// A class which mocks [KoneksiInternetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKoneksiInternetService extends _i1.Mock
    implements _i8.KoneksiInternetService {
  MockKoneksiInternetService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> cekKoneksiLokal() =>
      (super.noSuchMethod(
            Invocation.method(#cekKoneksiLokal, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> cekInternet() =>
      (super.noSuchMethod(
            Invocation.method(#cekInternet, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
