// Mocks generated by Mockito 5.4.6 from annotations
// in wifi/test/admin/halaman_utama_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:connectivity_plus/connectivity_plus.dart' as _i8;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:wifi/shared/data/services/layanan_cek_sinkronisasi.dart' as _i2;
import 'package:wifi/shared/services/arsipkan_langganan_kadaluarsa_service.dart'
    as _i4;
import 'package:workmanager/src/workmanager_impl.dart' as _i5;
import 'package:workmanager_platform_interface/workmanager_platform_interface.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LayananCekSinkronisasi].
///
/// See the documentation for Mockito's code generation for more information.
class MockLayananCekSinkronisasi extends _i1.Mock
    implements _i2.LayananCekSinkronisasi {
  MockLayananCekSinkronisasi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> jalankanCekSinkronisasi() =>
      (super.noSuchMethod(
            Invocation.method(#jalankanCekSinkronisasi, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [ArsipLanggananKadaluarsaService].
///
/// See the documentation for Mockito's code generation for more information.
class MockArsipLanggananKadaluarsaService extends _i1.Mock
    implements _i4.ArsipLanggananKadaluarsaService {
  MockArsipLanggananKadaluarsaService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> prosesArsipLanggananKadaluarsa() =>
      (super.noSuchMethod(
            Invocation.method(#prosesArsipLanggananKadaluarsa, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [Workmanager].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkmanager extends _i1.Mock implements _i5.Workmanager {
  MockWorkmanager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initialize(
    Function? callbackDispatcher, {
    bool? isInDebugMode = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #initialize,
              [callbackDispatcher],
              {#isInDebugMode: isInDebugMode},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void executeTask(_i5.BackgroundTaskHandler? backgroundTaskHandler) =>
      super.noSuchMethod(
        Invocation.method(#executeTask, [backgroundTaskHandler]),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> registerOneOffTask(
    String? uniqueName,
    String? taskName, {
    Map<String, dynamic>? inputData,
    Duration? initialDelay,
    _i6.Constraints? constraints,
    _i6.ExistingWorkPolicy? existingWorkPolicy,
    _i6.BackoffPolicy? backoffPolicy,
    Duration? backoffPolicyDelay,
    String? tag,
    _i6.OutOfQuotaPolicy? outOfQuotaPolicy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #registerOneOffTask,
              [uniqueName, taskName],
              {
                #inputData: inputData,
                #initialDelay: initialDelay,
                #constraints: constraints,
                #existingWorkPolicy: existingWorkPolicy,
                #backoffPolicy: backoffPolicy,
                #backoffPolicyDelay: backoffPolicyDelay,
                #tag: tag,
                #outOfQuotaPolicy: outOfQuotaPolicy,
              },
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> registerPeriodicTask(
    String? uniqueName,
    String? taskName, {
    Duration? frequency,
    Duration? flexInterval,
    Map<String, dynamic>? inputData,
    Duration? initialDelay,
    _i6.Constraints? constraints,
    _i6.ExistingPeriodicWorkPolicy? existingWorkPolicy,
    _i6.BackoffPolicy? backoffPolicy,
    Duration? backoffPolicyDelay,
    String? tag,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #registerPeriodicTask,
              [uniqueName, taskName],
              {
                #frequency: frequency,
                #flexInterval: flexInterval,
                #inputData: inputData,
                #initialDelay: initialDelay,
                #constraints: constraints,
                #existingWorkPolicy: existingWorkPolicy,
                #backoffPolicy: backoffPolicy,
                #backoffPolicyDelay: backoffPolicyDelay,
                #tag: tag,
              },
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isScheduledByUniqueName(String? uniqueName) =>
      (super.noSuchMethod(
            Invocation.method(#isScheduledByUniqueName, [uniqueName]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> registerProcessingTask(
    String? uniqueName,
    String? taskName, {
    Duration? initialDelay,
    Map<String, dynamic>? inputData,
    _i6.Constraints? constraints,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #registerProcessingTask,
              [uniqueName, taskName],
              {
                #initialDelay: initialDelay,
                #inputData: inputData,
                #constraints: constraints,
              },
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelByUniqueName(String? uniqueName) =>
      (super.noSuchMethod(
            Invocation.method(#cancelByUniqueName, [uniqueName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelByTag(String? tag) =>
      (super.noSuchMethod(
            Invocation.method(#cancelByTag, [tag]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelAll() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> printScheduledTasks() =>
      (super.noSuchMethod(
            Invocation.method(#printScheduledTasks, []),
            returnValue: _i3.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#printScheduledTasks, []),
              ),
            ),
          )
          as _i3.Future<String>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i8.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i9.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i3.Stream<List<_i9.ConnectivityResult>>.empty(),
          )
          as _i3.Stream<List<_i9.ConnectivityResult>>);

  @override
  _i3.Future<List<_i9.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i3.Future<List<_i9.ConnectivityResult>>.value(
              <_i9.ConnectivityResult>[],
            ),
          )
          as _i3.Future<List<_i9.ConnectivityResult>>);
}
