// Mocks generated by Mockito 5.4.6 from annotations
// in wifi/test/admin/halaman/lainnya/paket_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter/src/widgets/navigator.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wifi/admin/data/sqlite.dart' as _i2;
import 'package:wifi/fitur/paket/model/paket_model.dart' as _i6;
import 'package:wifi/fitur/paket/operasi/paket_op_sqlite.dart' as _i4;
import 'package:wifi/shared/operasi/sqlite_operasi/base_op_sqlite.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSqliteDatabase_0 extends _i1.SmartFake
    implements _i2.SqliteDatabase {
  _FakeSqliteDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseOpSqlite_1 extends _i1.SmartFake implements _i3.BaseOpSqlite {
  _FakeBaseOpSqlite_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PaketOpSqlite].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaketOpSqlite extends _i1.Mock implements _i4.PaketOpSqlite {
  MockPaketOpSqlite() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SqliteDatabase get sqliteDb =>
      (super.noSuchMethod(
            Invocation.getter(#sqliteDb),
            returnValue: _FakeSqliteDatabase_0(
              this,
              Invocation.getter(#sqliteDb),
            ),
          )
          as _i2.SqliteDatabase);

  @override
  _i3.BaseOpSqlite get basOpSqlite =>
      (super.noSuchMethod(
            Invocation.getter(#basOpSqlite),
            returnValue: _FakeBaseOpSqlite_1(
              this,
              Invocation.getter(#basOpSqlite),
            ),
          )
          as _i3.BaseOpSqlite);

  @override
  _i5.Future<void> tambahPaket(
    _i6.PaketModel? paket, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#tambahPaket, [paket], {#dariServer: dariServer}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.PaketModel>> ambilSemua() =>
      (super.noSuchMethod(
            Invocation.method(#ambilSemua, []),
            returnValue: _i5.Future<List<_i6.PaketModel>>.value(
              <_i6.PaketModel>[],
            ),
          )
          as _i5.Future<List<_i6.PaketModel>>);

  @override
  _i5.Future<List<_i6.PaketModel>> ambilBerdasarkanAktif() =>
      (super.noSuchMethod(
            Invocation.method(#ambilBerdasarkanAktif, []),
            returnValue: _i5.Future<List<_i6.PaketModel>>.value(
              <_i6.PaketModel>[],
            ),
          )
          as _i5.Future<List<_i6.PaketModel>>);

  @override
  _i5.Future<List<_i6.PaketModel>> ambilPaketPublik() =>
      (super.noSuchMethod(
            Invocation.method(#ambilPaketPublik, []),
            returnValue: _i5.Future<List<_i6.PaketModel>>.value(
              <_i6.PaketModel>[],
            ),
          )
          as _i5.Future<List<_i6.PaketModel>>);

  @override
  _i5.Future<_i6.PaketModel?> ambilBerdasarkanId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#ambilBerdasarkanId, [id]),
            returnValue: _i5.Future<_i6.PaketModel?>.value(),
          )
          as _i5.Future<_i6.PaketModel?>);

  @override
  _i5.Future<void> perbaruiPaket(
    _i6.PaketModel? paket, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #perbaruiPaket,
              [paket],
              {#dariServer: dariServer},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> hapusSementara(String? id, {bool? dariServer = false}) =>
      (super.noSuchMethod(
            Invocation.method(#hapusSementara, [id], {#dariServer: dariServer}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> hapusSementaraSemua({bool? dariServer = false}) =>
      (super.noSuchMethod(
            Invocation.method(#hapusSementaraSemua, [], {
              #dariServer: dariServer,
            }),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> hapus(String? id, {bool? dariServer = false}) =>
      (super.noSuchMethod(
            Invocation.method(#hapus, [id], {#dariServer: dariServer}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> hapusSemua({bool? dariServer = false}) =>
      (super.noSuchMethod(
            Invocation.method(#hapusSemua, [], {#dariServer: dariServer}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.PaketModel>> ambilPerubahanSejak(DateTime? since) =>
      (super.noSuchMethod(
            Invocation.method(#ambilPerubahanSejak, [since]),
            returnValue: _i5.Future<List<_i6.PaketModel>>.value(
              <_i6.PaketModel>[],
            ),
          )
          as _i5.Future<List<_i6.PaketModel>>);

  @override
  _i5.Future<void> sisipkanAtauPerbaruiBatch(
    List<_i6.PaketModel>? items, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sisipkanAtauPerbaruiBatch,
              [items],
              {#dariServer: dariServer},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.PaketModel>> ambilBerdasarkanBeberapaId(
    List<String>? ids,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#ambilBerdasarkanBeberapaId, [ids]),
            returnValue: _i5.Future<List<_i6.PaketModel>>.value(
              <_i6.PaketModel>[],
            ),
          )
          as _i5.Future<List<_i6.PaketModel>>);
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i7.NavigatorObserver {
  MockNavigatorObserver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void didPush(_i7.Route<dynamic>? route, _i7.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didPush, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didPop(_i7.Route<dynamic>? route, _i7.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didPop, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i7.Route<dynamic>? route,
    _i7.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didRemove, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didReplace({
    _i7.Route<dynamic>? newRoute,
    _i7.Route<dynamic>? oldRoute,
  }) => super.noSuchMethod(
    Invocation.method(#didReplace, [], {
      #newRoute: newRoute,
      #oldRoute: oldRoute,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTop(
    _i7.Route<dynamic>? topRoute,
    _i7.Route<dynamic>? previousTopRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didChangeTop, [topRoute, previousTopRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStartUserGesture(
    _i7.Route<dynamic>? route,
    _i7.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didStartUserGesture, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStopUserGesture() => super.noSuchMethod(
    Invocation.method(#didStopUserGesture, []),
    returnValueForMissingStub: null,
  );
}
