// Mocks generated by Mockito 5.4.6 from annotations
// in wifi/test/shared/data/services/pengecekan_data_baru_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i5;
import 'package:wifi/fitur/sinkronisasi/pengelola_sinkronisasi.dart' as _i2;
import 'package:wifi/shared/model/status_unggah_model.dart' as _i6;
import 'package:wifi/shared/operasi/sqlite_operasi/status_upload_op_sqlite.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PengelolaSinkronisasi].
///
/// See the documentation for Mockito's code generation for more information.
class MockPengelolaSinkronisasi extends _i1.Mock
    implements _i2.PengelolaSinkronisasi {
  MockPengelolaSinkronisasi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<DateTime> ambilWaktuTerakhirUnduhPreferensi() =>
      (super.noSuchMethod(
            Invocation.method(#ambilWaktuTerakhirUnduhPreferensi, []),
            returnValue: _i3.Future<DateTime>.value(
              _FakeDateTime_0(
                this,
                Invocation.method(#ambilWaktuTerakhirUnduhPreferensi, []),
              ),
            ),
          )
          as _i3.Future<DateTime>);

  @override
  _i3.Future<void> simpanWaktuTerakhirUnduhPreferensi(DateTime? waktu) =>
      (super.noSuchMethod(
            Invocation.method(#simpanWaktuTerakhirUnduhPreferensi, [waktu]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<DateTime> ambilWaktuTerakhirUnggahPreferensi() =>
      (super.noSuchMethod(
            Invocation.method(#ambilWaktuTerakhirUnggahPreferensi, []),
            returnValue: _i3.Future<DateTime>.value(
              _FakeDateTime_0(
                this,
                Invocation.method(#ambilWaktuTerakhirUnggahPreferensi, []),
              ),
            ),
          )
          as _i3.Future<DateTime>);

  @override
  _i3.Future<void> simpanWaktuTerakhirUnggahPreferensi(DateTime? waktu) =>
      (super.noSuchMethod(
            Invocation.method(#simpanWaktuTerakhirUnggahPreferensi, [waktu]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> resetWaktuSinkronisasiPreferensi() =>
      (super.noSuchMethod(
            Invocation.method(#resetWaktuSinkronisasiPreferensi, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [StatusUploadOpSqlite].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatusUploadOpSqlite extends _i1.Mock
    implements _i4.StatusUploadOpSqlite {
  MockStatusUploadOpSqlite() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> tandaiButuhUpload(
    bool? needUpload, {
    _i5.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #tandaiButuhUpload,
              [needUpload],
              {#transaction: transaction},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> ambilButuhUpload() =>
      (super.noSuchMethod(
            Invocation.method(#ambilButuhUpload, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> resetStatusUpload() =>
      (super.noSuchMethod(
            Invocation.method(#resetStatusUpload, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i6.StatusUnggahModel?> ambilStatusUpload() =>
      (super.noSuchMethod(
            Invocation.method(#ambilStatusUpload, []),
            returnValue: _i3.Future<_i6.StatusUnggahModel?>.value(),
          )
          as _i3.Future<_i6.StatusUnggahModel?>);
}
