// Mocks generated by Mockito 5.4.6 from annotations
// in wifi/test/shared/operasi/firebase_operasi/customer_op_firebase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wifi/shared/operasi/firebase_operasi/base_op_firebase.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDocumentReference_0<T extends Object?> extends _i1.SmartFake
    implements _i2.DocumentReference<T> {
  _FakeDocumentReference_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BaseOpFirebase].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseOpFirebase extends _i1.Mock implements _i3.BaseOpFirebase {
  MockBaseOpFirebase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DocumentReference<Object?>> add(
    String? collectionName,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [
            collectionName,
            data,
          ],
        ),
        returnValue: _i4.Future<_i2.DocumentReference<Object?>>.value(
            _FakeDocumentReference_0<Object?>(
          this,
          Invocation.method(
            #add,
            [
              collectionName,
              data,
            ],
          ),
        )),
      ) as _i4.Future<_i2.DocumentReference<Object?>>);

  @override
  _i4.Future<void> insert(
    String? collectionName,
    String? docId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [
            collectionName,
            docId,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> update(
    String? collectionName,
    String? docId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            collectionName,
            docId,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> softDelete(
    String? collectionName,
    String? docId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #softDelete,
          [
            collectionName,
            docId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> delete(
    String? collectionName,
    String? docId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [
            collectionName,
            docId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> softDeleteAll(String? collectionName) => (super.noSuchMethod(
        Invocation.method(
          #softDeleteAll,
          [collectionName],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> insertOrUpdateBatch(
    String? collectionName,
    List<Map<String, dynamic>>? items,
    String? idKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertOrUpdateBatch,
          [
            collectionName,
            items,
            idKey,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
