// Mocks generated by Mockito 5.4.6 from annotations
// in wifi/test/fitur/pelanggan/operasi/pelanggan_op_sqlite_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:sqflite/sqflite.dart' as _i3;
import 'package:wifi/admin/data/sqlite.dart' as _i6;
import 'package:wifi/shared/operasi/sqlite_operasi/base_op_sqlite.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabase_1 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BaseOpSqlite].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseOpSqlite extends _i1.Mock implements _i4.BaseOpSqlite {
  MockBaseOpSqlite() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<T> operasiKompleks<T>(
    _i2.Future<T> Function(_i3.Transaction)? aksiKustom, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #operasiKompleks,
              [aksiKustom],
              {#dariServer: dariServer},
            ),
            returnValue:
                _i5.ifNotNull(
                  _i5.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #operasiKompleks,
                      [aksiKustom],
                      {#dariServer: dariServer},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #operasiKompleks,
                    [aksiKustom],
                    {#dariServer: dariServer},
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<void> sisipkan(
    String? table,
    Map<String, dynamic>? data, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sisipkan,
              [table, data],
              {#dariServer: dariServer},
            ),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> update(
    String? table,
    Map<String, dynamic>? data,
    String? id, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #update,
              [table, data, id],
              {#dariServer: dariServer},
            ),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> delete(
    String? table,
    String? id, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table, id], {#dariServer: dariServer}),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> softDelete(
    String? table,
    String? id, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #softDelete,
              [table, id],
              {#dariServer: dariServer},
            ),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<int> softDeleteAll(String? table, {bool? dariServer = false}) =>
      (super.noSuchMethod(
            Invocation.method(
              #softDeleteAll,
              [table],
              {#dariServer: dariServer},
            ),
            returnValue: _i2.Future<int>.value(0),
          )
          as _i2.Future<int>);

  @override
  _i2.Future<void> sisipkanAtauPerbaruiBatch(
    String? table,
    List<Map<String, dynamic>>? dataList, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sisipkanAtauPerbaruiBatch,
              [table, dataList],
              {#dariServer: dariServer},
            ),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);
}

/// A class which mocks [SqliteDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSqliteDatabase extends _i1.Mock implements _i6.SqliteDatabase {
  MockSqliteDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<_i3.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i2.Future<_i3.Database>.value(
              _FakeDatabase_1(this, Invocation.getter(#database)),
            ),
          )
          as _i2.Future<_i3.Database>);

  @override
  void debugSetDatabaseNull() => super.noSuchMethod(
    Invocation.method(#debugSetDatabaseNull, []),
    returnValueForMissingStub: null,
  );

  @override
  _i2.Future<void> membuatTabel(_i3.Database? db, int? version) =>
      (super.noSuchMethod(
            Invocation.method(#membuatTabel, [db, version]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);
}
