// Mocks generated by Mockito 5.4.6 from annotations
// in wifi/test/fitur/akun/provider/akun_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter/material.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i2;
import 'package:wifi/fitur/pelanggan/model/pelanggan_model.dart' as _i6;
import 'package:wifi/user/services/storage/layanan_penyimpanan_lokal.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSharedPreferences_0 extends _i1.SmartFake
    implements _i2.SharedPreferences {
  _FakeSharedPreferences_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LayananPenyimpananLokal].
///
/// See the documentation for Mockito's code generation for more information.
class MockLayananPenyimpananLokal extends _i1.Mock
    implements _i3.LayananPenyimpananLokal {
  @override
  _i2.SharedPreferences get prefs =>
      (super.noSuchMethod(
            Invocation.getter(#prefs),
            returnValue: _FakeSharedPreferences_0(
              this,
              Invocation.getter(#prefs),
            ),
            returnValueForMissingStub: _FakeSharedPreferences_0(
              this,
              Invocation.getter(#prefs),
            ),
          )
          as _i2.SharedPreferences);

  @override
  _i4.Future<void> simpanModeTema(_i5.ThemeMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#simpanModeTema, [mode]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.ThemeMode> ambilModeTema() =>
      (super.noSuchMethod(
            Invocation.method(#ambilModeTema, []),
            returnValue: _i4.Future<_i5.ThemeMode>.value(_i5.ThemeMode.system),
            returnValueForMissingStub: _i4.Future<_i5.ThemeMode>.value(
              _i5.ThemeMode.system,
            ),
          )
          as _i4.Future<_i5.ThemeMode>);

  @override
  _i4.Future<void> simpanAkun(_i6.PelangganModel? pelanggan) =>
      (super.noSuchMethod(
            Invocation.method(#simpanAkun, [pelanggan]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> simpanAkunSaatIni(_i6.PelangganModel? pelanggan) =>
      (super.noSuchMethod(
            Invocation.method(#simpanAkunSaatIni, [pelanggan]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.PelangganModel>> ambilDaftarAkun() =>
      (super.noSuchMethod(
            Invocation.method(#ambilDaftarAkun, []),
            returnValue: _i4.Future<List<_i6.PelangganModel>>.value(
              <_i6.PelangganModel>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i6.PelangganModel>>.value(
                  <_i6.PelangganModel>[],
                ),
          )
          as _i4.Future<List<_i6.PelangganModel>>);

  @override
  _i4.Future<void> hapusAkun(String? idPengguna) =>
      (super.noSuchMethod(
            Invocation.method(#hapusAkun, [idPengguna]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> hapusAkunSaatIni() =>
      (super.noSuchMethod(
            Invocation.method(#hapusAkunSaatIni, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> hapusTokenLogin() =>
      (super.noSuchMethod(
            Invocation.method(#hapusTokenLogin, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i6.PelangganModel?> ambilAkunLogin() =>
      (super.noSuchMethod(
            Invocation.method(#ambilAkunLogin, []),
            returnValue: _i4.Future<_i6.PelangganModel?>.value(),
            returnValueForMissingStub: _i4.Future<_i6.PelangganModel?>.value(),
          )
          as _i4.Future<_i6.PelangganModel?>);

  @override
  _i4.Future<void> hapusSemuaData() =>
      (super.noSuchMethod(
            Invocation.method(#hapusSemuaData, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
