// Mocks generated by Mockito 5.4.6 from annotations
// in wifi/test/admin/halaman/event/detail_event_a_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wifi/shared/model/event_model.dart' as _i4;
import 'package:wifi/shared/operasi/firebase_operasi/event_op_supabase.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [EventOpSupabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventOpSupabase extends _i1.Mock implements _i2.EventOpSupabase {
  MockEventOpSupabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.EventModel>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i3.Future<List<_i4.EventModel>>.value(<_i4.EventModel>[]),
      ) as _i3.Future<List<_i4.EventModel>>);

  @override
  _i3.Stream<List<_i4.EventModel>> getRealtimeStream() => (super.noSuchMethod(
        Invocation.method(
          #getRealtimeStream,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.EventModel>>.empty(),
      ) as _i3.Stream<List<_i4.EventModel>>);

  @override
  _i3.Future<_i4.EventModel?> getActive() => (super.noSuchMethod(
        Invocation.method(
          #getActive,
          [],
        ),
        returnValue: _i3.Future<_i4.EventModel?>.value(),
      ) as _i3.Future<_i4.EventModel?>);

  @override
  _i3.Future<_i4.EventModel?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i3.Future<_i4.EventModel?>.value(),
      ) as _i3.Future<_i4.EventModel?>);

  @override
  _i3.Future<void> addEvent(_i4.EventModel? event) => (super.noSuchMethod(
        Invocation.method(
          #addEvent,
          [event],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> update(_i4.EventModel? event) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [event],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteEvent(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteEvent,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
