// Mocks generated by Mockito 5.4.6 from annotations
// in wifi/test/admin/halaman/form/form_pelanggan_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter/src/widgets/navigator.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wifi/admin/data/sqlite.dart' as _i2;
import 'package:wifi/fitur/pelanggan/model/pelanggan_model.dart' as _i5;
import 'package:wifi/fitur/pelanggan/operasi/pelanggan_op_sqlite.dart' as _i3;
import 'package:wifi/fitur/sinkronisasi/layanan_cek_sinkronisasi.dart' as _i7;
import 'package:wifi/shared/services/koneksi_internet_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSqliteDatabase_0 extends _i1.SmartFake
    implements _i2.SqliteDatabase {
  _FakeSqliteDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PelangganOpSqlite].
///
/// See the documentation for Mockito's code generation for more information.
class MockPelangganOpSqlite extends _i1.Mock implements _i3.PelangganOpSqlite {
  MockPelangganOpSqlite() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SqliteDatabase get sqliteDb =>
      (super.noSuchMethod(
            Invocation.getter(#sqliteDb),
            returnValue: _FakeSqliteDatabase_0(
              this,
              Invocation.getter(#sqliteDb),
            ),
          )
          as _i2.SqliteDatabase);

  @override
  _i4.Future<void> tambahPelanggan(
    _i5.PelangganModel? pelanggan, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #tambahPelanggan,
              [pelanggan],
              {#dariServer: dariServer},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.PelangganModel>> ambilSemua({
    bool? tampilkanYangDiarsip = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#ambilSemua, [], {
              #tampilkanYangDiarsip: tampilkanYangDiarsip,
            }),
            returnValue: _i4.Future<List<_i5.PelangganModel>>.value(
              <_i5.PelangganModel>[],
            ),
          )
          as _i4.Future<List<_i5.PelangganModel>>);

  @override
  _i4.Future<_i5.PelangganModel?> ambilBerdasarkanId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#ambilBerdasarkanId, [id]),
            returnValue: _i4.Future<_i5.PelangganModel?>.value(),
          )
          as _i4.Future<_i5.PelangganModel?>);

  @override
  _i4.Future<void> perbaruiPelanggan(
    _i5.PelangganModel? pelanggan, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #perbaruiPelanggan,
              [pelanggan],
              {#dariServer: dariServer},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> softDelete(String? id, {bool? dariServer = false}) =>
      (super.noSuchMethod(
            Invocation.method(#softDelete, [id], {#dariServer: dariServer}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> softDeleteSemua({bool? dariServer = false}) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteSemua, [], {#dariServer: dariServer}),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.PelangganModel>> ambilPerubahanSejak(DateTime? sejak) =>
      (super.noSuchMethod(
            Invocation.method(#ambilPerubahanSejak, [sejak]),
            returnValue: _i4.Future<List<_i5.PelangganModel>>.value(
              <_i5.PelangganModel>[],
            ),
          )
          as _i4.Future<List<_i5.PelangganModel>>);

  @override
  _i4.Future<void> sisipkanAtauPerbaruiBatch(
    List<_i5.PelangganModel>? pelanggan, {
    bool? dariServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sisipkanAtauPerbaruiBatch,
              [pelanggan],
              {#dariServer: dariServer},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.PelangganModel>> ambilPelangganBerdasarkanId(
    List<String>? ids,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#ambilPelangganBerdasarkanId, [ids]),
            returnValue: _i4.Future<List<_i5.PelangganModel>>.value(
              <_i5.PelangganModel>[],
            ),
          )
          as _i4.Future<List<_i5.PelangganModel>>);
}

/// A class which mocks [KoneksiInternetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKoneksiInternetService extends _i1.Mock
    implements _i6.KoneksiInternetService {
  MockKoneksiInternetService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> cekKoneksiLokal() =>
      (super.noSuchMethod(
            Invocation.method(#cekKoneksiLokal, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> cekInternet() =>
      (super.noSuchMethod(
            Invocation.method(#cekInternet, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [LayananCekSinkronisasi].
///
/// See the documentation for Mockito's code generation for more information.
class MockLayananCekSinkronisasi extends _i1.Mock
    implements _i7.LayananCekSinkronisasi {
  MockLayananCekSinkronisasi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> jalankanCekSinkronisasi() =>
      (super.noSuchMethod(
            Invocation.method(#jalankanCekSinkronisasi, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i8.NavigatorObserver {
  MockNavigatorObserver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void didPush(_i8.Route<dynamic>? route, _i8.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didPush, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didPop(_i8.Route<dynamic>? route, _i8.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didPop, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i8.Route<dynamic>? route,
    _i8.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didRemove, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didReplace({
    _i8.Route<dynamic>? newRoute,
    _i8.Route<dynamic>? oldRoute,
  }) => super.noSuchMethod(
    Invocation.method(#didReplace, [], {
      #newRoute: newRoute,
      #oldRoute: oldRoute,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTop(
    _i8.Route<dynamic>? topRoute,
    _i8.Route<dynamic>? previousTopRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didChangeTop, [topRoute, previousTopRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStartUserGesture(
    _i8.Route<dynamic>? route,
    _i8.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didStartUserGesture, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStopUserGesture() => super.noSuchMethod(
    Invocation.method(#didStopUserGesture, []),
    returnValueForMissingStub: null,
  );
}
