'''
// Mocks generated by Mockito 5.4.4 from annotations
// in wifi/test/user/page/edit_profile_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:wifi/fitur/pelanggan/model/customer_model.dart' as _i7;
import 'package:wifi/shared/model/save_result_model.dart' as _i3;
import 'package:wifi/shared/operasi/firebase_operasi/customer_op_firebase.dart'
    as _i5;
import 'package:wifi/shared/services/koneksi_internet_service.dart' as _i4;
import 'package:wifi/shared/sqflite/base_operation.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseOperation_0<T> extends _i1.SmartFake
    implements _i2.BaseOperation<T> {
  _FakeBaseOperation_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveResult_1 extends _i1.SmartFake implements _i3.SaveResult {
  _FakeSaveResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [KoneksiInternetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKoneksiInternetService extends _i1.Mock
    implements _i4.KoneksiInternetService {}

/// A class which mocks [CustomerOpFirebase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerOpFirebase extends _i1.Mock implements _i5.CustomerOpFirebase {
  MockCustomerOpFirebase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BaseOperation<dynamic> get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeBaseOperation_0<dynamic>(
          this,
          Invocation.getter(#db),
        ),
      ) as _i2.BaseOperation<dynamic>);

  @override
  set db(_i2.BaseOperation<dynamic>? _db) => super.noSuchMethod(
        Invocation.setter(
          #db,
          _db,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<List<_i7.CustomerModel>> getAllCustomers() => (super.noSuchMethod(
        Invocation.method(
          #getAllCustomers,
          [],
        ),
        returnValue:
            _i6.Future.value(<_i7.CustomerModel>[]),
      ) as _i6.Future<List<_i7.CustomerModel>>);

  @override
  _i6.Future<_i7.CustomerModel?> getCustomerById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCustomerById,
          [id],
        ),
        returnValue: _i6.Future.value(),
      ) as _i6.Future<_i7.CustomerModel?>);

  @override
  _i6.Future<List<_i7.CustomerModel>> getCustomersByDate(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCustomersByDate,
          [
            startDate,
            endDate,
          ],
        ),
        returnValue:
            _i6.Future.value(<_i7.CustomerModel>[]),
      ) as _i6.Future<List<_i7.CustomerModel>>);

  @override
  _i6.Future<List<_i7.CustomerModel>> getActiveCustomers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveCustomers,
          [],
        ),
        returnValue:
            _i6.Future.value(<_i7.CustomerModel>[]),
      ) as _i6.Future<List<_i7.CustomerModel>>);

  @override
  _i6.Future<void> updateCustomer(_i7.CustomerModel? customer) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCustomer,
          [customer],
        ),
        returnValue: _i6.Future.value(),
        returnValueForMissingStub: _i6.Future.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> addCustomer(_i7.CustomerModel? customer) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCustomer,
          [customer],
        ),
        returnValue: _i6.Future.value(),
        returnValueForMissingStub: _i6.Future.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteCustomer(String? customerId) => (super.noSuchMethod(
        Invocation.method(
          #deleteCustomer,
          [customerId],
        ),
        returnValue: _i6.Future.value(),
        returnValueForMissingStub: _i6.Future.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.SaveResult> saveData(
    _i8.Ref<Object?>? ref, {
    required List<_i7.CustomerModel>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveData,
          [ref],
          {#data: data},
        ),
        returnValue: _i6.Future.value(_FakeSaveResult_1(
          this,
          Invocation.method(
            #saveData,
            [ref],
            {#data: data},
          ),
        )),
      ) as _i6.Future<_i3.SaveResult>);

  @override
  _i6.Future<Map<String, int>> getCustomerStats() => (super.noSuchMethod(
        Invocation.method(
          #getCustomerStats,
          [],
        ),
        returnValue: _i6.Future.value(<String, int>{}),
      ) as _i6.Future<Map<String, int>>);

  @override
  _i6.Future<List<_i7.CustomerModel>> downloadData(
          _i8.Ref<Object?>? ref) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadData,
          [ref],
        ),
        returnValue:
            _i6.Future.value(<_i7.CustomerModel>[]),
      ) as _i6.Future<List<_i7.CustomerModel>>);

  @override
  String generateId() => (super.noSuchMethod(
        Invocation.method(
          #generateId,
          [],
        ),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #generateId,
            [],
          ),
        ),
      ) as String);
}

''