"""// path: test/user/page/login_page_test.mocks.dart
// Mocks generated by Mockito 5.4.4 from annotations
// in wifi/test/user/page/login_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:cloud_firestore/cloud_firestore.dart' as _i3;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wifi/fitur/akun/provider/akun_provider.dart' as _i13;
import 'package:wifi/fitur/pelanggan/core/user_activity_service.dart' as _i10;
import 'package:wifi/fitur/pelanggan/model/customer_model.dart' as _i7;
import 'package:wifi/shared/services/koneksi_internet_service.dart' as _i8;
import 'package:wifi/user/services/storage/layanan_penyimpanan_lokal.dart'
    as _i9;

import 'login_page_test.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MockFirebaseFirestore].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockFirebaseFirestore extends _i1.Mock
    implements _i2.MockFirebaseFirestore {
  @override
  _i3.CollectionReference<Map<String, dynamic>> collection(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #collection,
          [path],
        ),
        returnValue: _FakeCollectionReference_1<Map<String, dynamic>>(
          this,
          Invocation.method(
            #collection,
            [path],
          ),
        ),
        returnValueForMissingStub:
            _FakeCollectionReference_1<Map<String, dynamic>>(
          this,
          Invocation.method(
            #collection,
            [path],
          ),
        ),
      ) as _i3.CollectionReference<Map<String, dynamic>>);
}

/// A class which mocks [MockCollectionReference].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockCollectionReference<T extends Object?> extends _i1.Mock
    implements _i2.MockCollectionReference<T> {
  @override
  _i3.Query<T> where(
    Object? field, {
    Object? isEqualTo,
    Object? isNotEqualTo,
    Object? isLessThan,
    Object? isLessThanOrEqualTo,
    Object? isGreaterThan,
    Object? isGreaterThanOrEqualTo,
    Object? arrayContains,
    Iterable<Object?>? arrayContainsAny,
    Iterable<Object?>? whereIn,
    Iterable<Object?>? whereNotIn,
    bool? isNull,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #where,
          [field],
          {
            #isEqualTo: isEqualTo,
            #isNotEqualTo: isNotEqualTo,
            #isLessThan: isLessThan,
            #isLessThanOrEqualTo: isLessThanOrEqualTo,
            #isGreaterThan: isGreaterThan,
            #isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
            #arrayContains: arrayContains,
            #arrayContainsAny: arrayContainsAny,
            #whereIn: whereIn,
            #whereNotIn: whereNotIn,
            #isNull: isNull,
          },
        ),
        returnValue: _FakeQuery_2<T>(
          this,
          Invocation.method(
            #where,
            [field],
            {
              #isEqualTo: isEqualTo,
              #isNotEqualTo: isNotEqualTo,
              #isLessThan: isLessThan,
              #isLessThanOrEqualTo: isLessThanOrEqualTo,
              #isGreaterThan: isGreaterThan,
              #isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
              #arrayContains: arrayContains,
              #arrayContainsAny: arrayContainsAny,
              #whereIn: whereIn,
              #whereNotIn: whereNotIn,
              #isNull: isNull,
            },
          ),
        ),
        returnValueForMissingStub: _FakeQuery_2<T>(
          this,
          Invocation.method(
            #where,
            [field],
            {
              #isEqualTo: isEqualTo,
              #isNotEqualTo: isNotEqualTo,
              #isLessThan: isLessThan,
              #isLessThanOrEqualTo: isLessThanOrEqualTo,
              #isGreaterThan: isGreaterThan,
              #isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
              #arrayContains: arrayContains,
              #arrayContainsAny: arrayContainsAny,
              #whereIn: whereIn,
              #whereNotIn: whereNotIn,
              #isNull: isNull,
            },
          ),
        ),
      ) as _i3.Query<T>);
}

/// A class which mocks [MockQuery].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockQuery<T extends Object?> extends _i1.Mock
    implements _i2.MockQuery<T> {
  @override
  _i3.Query<T> where(
    Object? field, {
    Object? isEqualTo,
    Object? isNotEqualTo,
    Object? isLessThan,
    Object? isLessThanOrEqualTo,
    Object? isGreaterThan,
    Object? isGreaterThanOrEqualTo,
    Object? arrayContains,
    Iterable<Object?>? arrayContainsAny,
    Iterable<Object?>? whereIn,
    Iterable<Object?>? whereNotIn,
    bool? isNull,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #where,
          [field],
          {
            #isEqualTo: isEqualTo,
            #isNotEqualTo: isNotEqualTo,
            #isLessThan: isLessThan,
            #isLessThanOrEqualTo: isLessThanOrEqualTo,
            #isGreaterThan: isGreaterThan,
            #isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
            #arrayContains: arrayContains,
            #arrayContainsAny: arrayContainsAny,
            #whereIn: whereIn,
            #whereNotIn: whereNotIn,
            #isNull: isNull,
          },
        ),
        returnValue: _FakeQuery_2<T>(
          this,
          Invocation.method(
            #where,
            [field],
            {
              #isEqualTo: isEqualTo,
              #isNotEqualTo: isNotEqualTo,
              #isLessThan: isLessThan,
              #isLessThanOrEqualTo: isLessThanOrEqualTo,
              #isGreaterThan: isGreaterThan,
              #isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
              #arrayContains: arrayContains,
              #arrayContainsAny: arrayContainsAny,
              #whereIn: whereIn,
              #whereNotIn: whereNotIn,
              #isNull: isNull,
            },
          ),
        ),
        returnValueForMissingStub: _FakeQuery_2<T>(
          this,
          Invocation.method(
            #where,
            [field],
            {
              #isEqualTo: isEqualTo,
              #isNotEqualTo: isNotEqualTo,
              #isLessThan: isLessThan,
              #isLessThanOrEqualTo: isLessThanOrEqualTo,
              #isGreaterThan: isGreaterThan,
              #isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
              #arrayContains: arrayContains,
              #arrayContainsAny: arrayContainsAny,
              #whereIn: whereIn,
              #whereNotIn: whereNotIn,
              #isNull: isNull,
            },
          ),
        ),
      ) as _i3.Query<T>);

  @override
  _i3.Query<T> limit(int? limit) => (super.noSuchMethod(
        Invocation.method(
          #limit,
          [limit],
        ),
        returnValue: _FakeQuery_2<T>(
          this,
          Invocation.method(
            #limit,
            [limit],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_2<T>(
          this,
          Invocation.method(
            #limit,
            [limit],
          ),
        ),
      ) as _i3.Query<T>);

  @override
  _i6.Future<_i3.QuerySnapshot<T>> get(
          [_i3.GetOptions? options]) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [options],
        ),
        returnValue: _i6.Future.value(_FakeQuerySnapshot_3<T>(
          this,
          Invocation.method(
            #get,
            [options],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future.value(_FakeQuerySnapshot_3<T>(
          this,
          Invocation.method(
            #get,
            [options],
          ),
        )),
      ) as _i6.Future<_i3.QuerySnapshot<T>>);
}

/// A class which mocks [MockQuerySnapshot].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockQuerySnapshot<T extends Object?> extends _i1.Mock
    implements _i2.MockQuerySnapshot<T> {
  @override
  List<_i3.QueryDocumentSnapshot<T>> get docs => (super.noSuchMethod(
        Invocation.getter(#docs),
        returnValue: <_i3.QueryDocumentSnapshot<T>>[],
        returnValueForMissingStub: <_i3.QueryDocumentSnapshot<T>>[],
      ) as List<_i3.QueryDocumentSnapshot<T>>);
}

/// A class which mocks [MockQueryDocumentSnapshot].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockQueryDocumentSnapshot<T extends Object?> extends _i1.Mock
    implements _i2.MockQueryDocumentSnapshot<T> {
  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);

  @override
  T data() => (super.noSuchMethod(
        Invocation.method(
          #data,
          [],
        ),
        returnValue: _i1.dummyValue<T>(
          this,
          Invocation.method(
            #data,
            [],
          ),
        ),
        returnValueForMissingStub: _i1.dummyValue<T>(
          this,
          Invocation.method(
            #data,
            [],
          ),
        ),
      ) as T);
}

/// A class which mocks [PengelolaAkun].
///
/// See the documentation for Mockito's code generation for more information.
class MockPengelolaAkun extends _i1.Mock implements _i13.PengelolaAkun {
  @override
  _i6.Future<void> login(_i7.CustomerModel? customer) => (super.noSuchMethod(
        Invocation.method(
          #login,
          [customer],
        ),
        returnValue: _i6.Future.value(),
        returnValueForMissingStub: _i6.Future.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [KoneksiInternetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKoneksiInternetService extends _i1.Mock
    implements _i8.KoneksiInternetService {
  @override
  _i6.Future<bool> cekInternet(_i11.Ref<Object?>? ref) => (super.noSuchMethod(
        Invocation.method(
          #cekInternet,
          [ref],
        ),
        returnValue: _i6.Future.value(false),
        returnValueForMissingStub: _i6.Future.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [LayananPenyimpananLokal].
///
/// See the documentation for Mockito's code generation for more information.
class MockLayananPenyimpananLokal extends _i1.Mock
    implements _i9.LayananPenyimpananLokal {
  @override
  _i6.Future<List<_i7.CustomerModel>> ambilDaftarAkun() => (super.noSuchMethod(
        Invocation.method(
          #ambilDaftarAkun,
          [],
        ),
        returnValue: _i6.Future.value(<_i7.CustomerModel>[]),
        returnValueForMissingStub: _i6.Future.value(<_i7.CustomerModel>[]),
      ) as _i6.Future<List<_i7.CustomerModel>>);
}

/// A class which mocks [UserActivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserActivityService extends _i1.Mock
    implements _i10.UserActivityService {
  @override
  void pingActivity(
    String? customerId, {
    bool? force = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #pingActivity,
          [customerId],
          {#force: force},
        ),
        returnValueForMissingStub: null,
      );
}

""