// path: test/user/page/main_page_test.mocks.dart

// Mocks generated by Mockito 5.4.4 from annotations
// in wifi/test/user/page/main_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wifi/fitur/notfikasi/notifikasi_servis.dart' as _i3;
import 'package:wifi/fitur/pelanggan/core/user_activity_service.dart' as _i5;
import 'package:wifi/user/widget/ads/app_open/app_lifecycle_reactor.dart'
    as _i6;
import 'package:wifi/user/widget/ads/app_open/app_open_ad_service.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFlutterLocalNotificationsPlugin extends _i1.SmartFake
    implements _i2.FlutterLocalNotificationsPlugin {
  _FakeFlutterLocalNotificationsPlugin(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NotifikasiServis].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotifikasiServis extends _i1.Mock implements _i3.LayananNotifikasi {
  MockNotifikasiServis() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlutterLocalNotificationsPlugin get notifikasiLokal =>
      (super.noSuchMethod(
        Invocation.getter(#notifikasiLokal),
        returnValue: _FakeFlutterLocalNotificationsPlugin(
          this,
          Invocation.getter(#notifikasiLokal),
        ),
      ) as _i2.FlutterLocalNotificationsPlugin);

  @override
  _i4.Future<void> inisialisasi() => (super.noSuchMethod(
        Invocation.method(
          #inisialisasi,
          [],
        ),
        returnValue: _i4.Future.value(),
        returnValueForMissingStub: _i4.Future.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [UserActivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserActivityService extends _i1.Mock
    implements _i5.UserActivityService {
  MockUserActivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> pingActivity(String? customerId) => (super.noSuchMethod(
        Invocation.method(
          #pingActivity,
          [customerId],
        ),
        returnValue: _i4.Future.value(),
        returnValueForMissingStub: _i4.Future.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [AppLifecycleReactor].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLifecycleReactor extends _i1.Mock
    implements _i6.AppLifecycleReactor {
  MockAppLifecycleReactor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.LayananIklanBukaAplikasi get appOpenAdService => (super.noSuchMethod(
        Invocation.getter(#appOpenAdService),
        returnValue: _FakeLayananIklanBukaAplikasi_0(
          this,
          Invocation.getter(#appOpenAdService),
        ),
      ) as _i7.LayananIklanBukaAplikasi);

  @override
  void listenToAppStateChanges() => super.noSuchMethod(
        Invocation.method(
          #listenToAppStateChanges,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LayananIklanBukaAplikasi].
///
/// See the documentation for Mockito's code generation for more information.
class MockLayananIklanBukaAplikasi extends _i1.Mock
    implements _i7.LayananIklanBukaAplikasi {
  MockLayananIklanBukaAplikasi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> loadAd() => (super.noSuchMethod(
        Invocation.method(
          #loadAd,
          [],
        ),
        returnValue: _i4.Future.value(),
        returnValueForMissingStub: _i4.Future.value(),
      ) as _i4.Future<void>);

  @override
  void showAdIfAvailable() => super.noSuchMethod(
        Invocation.method(
          #showAdIfAvailable,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
